"""Pydantic 스키마 (request/response DTO)."""

from app.schemas.ai import (
    AIGenerationMetadata,
    AIGenerationResponse,
    AIRequestLogItem,
    AIRequestLogListResponse,
    ExplainRequest,
    QARequest,
)
from app.schemas.auth import (
    AccessTokenResponse,
    LoginRequest,
    PasswordChangeRequest,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshTokenRequest,
    RegisterRequest,
    TokenResponse,
)
from app.schemas.common import ErrorResponse, MessageResponse
from app.schemas.diagnostic import (
    AIProfileResponse,
    DiagnosticAnswerInput,
    DiagnosticResultResponse,
    DiagnosticStartResponse,
    DiagnosticSubmitRequest,
    WeakAreaItem,
)
from app.schemas.learning_history import (
    AnswerSubmitRequest,
    AnswerSubmitResponse,
    LearningHistoryItem,
    LearningHistoryListResponse,
    LearningStatsResponse,
    StatsBucket,
    StatsPeriod,
    SubjectBreakdown,
    WrongAnswerItem,
    WrongAnswerListResponse,
)
from app.schemas.question import (
    BulkUploadResult,
    QuestionCreate,
    QuestionListResponse,
    QuestionPublic,
    QuestionResponse,
    QuestionUpdate,
)
from app.schemas.user import UserBase, UserMe, UserPublic

__all__ = [
    "AIGenerationMetadata",
    "AIGenerationResponse",
    "AIProfileResponse",
    "AIRequestLogItem",
    "AIRequestLogListResponse",
    "AccessTokenResponse",
    "AnswerSubmitRequest",
    "AnswerSubmitResponse",
    "BulkUploadResult",
    "DiagnosticAnswerInput",
    "DiagnosticResultResponse",
    "DiagnosticStartResponse",
    "DiagnosticSubmitRequest",
    "ErrorResponse",
    "ExplainRequest",
    "LearningHistoryItem",
    "LearningHistoryListResponse",
    "LearningStatsResponse",
    "LoginRequest",
    "MessageResponse",
    "PasswordChangeRequest",
    "PasswordResetConfirm",
    "PasswordResetRequest",
    "QARequest",
    "QuestionCreate",
    "QuestionListResponse",
    "QuestionPublic",
    "QuestionResponse",
    "QuestionUpdate",
    "RefreshTokenRequest",
    "RegisterRequest",
    "StatsBucket",
    "StatsPeriod",
    "SubjectBreakdown",
    "TokenResponse",
    "UserBase",
    "UserMe",
    "UserPublic",
    "WeakAreaItem",
    "WrongAnswerItem",
    "WrongAnswerListResponse",
]
