"""치위생과 시드 문제 (60문항).

구강해부학 8 / 구강조직발생학 6 / 구강병리학 8 / 구강위생학 12 /
치주관리학 10 / 예방치과학 10 / 의료법규 6
"""

from app.models.enums import Department, Difficulty, QuestionType

DEPT = Department.DENTAL_HYGIENE
TYPE = QuestionType.SINGLE_CHOICE
SOURCE = "샘플 시드 (Day 3)"

DH_QUESTIONS = [
    # ============ 구강해부학 (8) ============
    {
        "subject": "구강해부학", "unit": "치아", "difficulty": Difficulty.EASY,
        "question_text": "성인의 영구치는 모두 몇 개인가?",
        "choices": ["20개", "24개", "28개", "32개", "36개"],
        "correct_answer": 3,
        "explanation": "성인 영구치는 사랑니 포함 32개 (사랑니 제외 시 28개).",
        "tags": ["해부", "치아", "영구치"],
    },
    {
        "subject": "구강해부학", "unit": "치아", "difficulty": Difficulty.MEDIUM,
        "question_text": "유치는 모두 몇 개인가?",
        "choices": ["16개", "18개", "20개", "24개", "28개"],
        "correct_answer": 2,
        "explanation": "유치(deciduous teeth)는 20개. 영구 어금니의 자리에 유구치만 있다.",
        "tags": ["해부", "치아", "유치"],
    },
    {
        "subject": "구강해부학", "unit": "치아", "difficulty": Difficulty.MEDIUM,
        "question_text": "치아의 가장 단단한 조직은?",
        "choices": ["상아질(dentin)", "법랑질(enamel)", "백악질(cementum)", "치수(pulp)", "치조골"],
        "correct_answer": 1,
        "explanation": "법랑질은 인체에서 가장 단단한 조직 (Mohs 5).",
        "tags": ["해부", "법랑질"],
    },
    {
        "subject": "구강해부학", "unit": "구강", "difficulty": Difficulty.MEDIUM,
        "question_text": "혀의 미각을 담당하는 뇌신경 중 혀 후방 1/3의 미각을 담당하는 것은?",
        "choices": ["삼차신경(V)", "안면신경(VII)", "설인신경(IX)", "미주신경(X)", "설하신경(XII)"],
        "correct_answer": 2,
        "explanation": "전방 2/3는 안면신경(VII) 고삭신경 분지, 후방 1/3은 설인신경(IX).",
        "tags": ["해부", "신경", "미각"],
    },
    {
        "subject": "구강해부학", "unit": "구강", "difficulty": Difficulty.HARD,
        "question_text": "악관절(TMJ)을 형성하는 뼈는?",
        "choices": [
            "측두골과 하악골",
            "측두골과 상악골",
            "두정골과 하악골",
            "전두골과 하악골",
            "후두골과 하악골",
        ],
        "correct_answer": 0,
        "explanation": "TMJ는 측두골(하악와) + 하악골(하악과두)로 구성.",
        "tags": ["해부", "TMJ"],
    },
    {
        "subject": "구강해부학", "unit": "치아", "difficulty": Difficulty.MEDIUM,
        "question_text": "FDI 표기법으로 우측 상악 첫 번째 큰어금니는?",
        "choices": ["#11", "#16", "#21", "#26", "#46"],
        "correct_answer": 1,
        "explanation": "FDI: 1사분면(우상)의 6번 = 16. 영구 제1대구치.",
        "tags": ["해부", "치아표기", "FDI"],
    },
    {
        "subject": "구강해부학", "unit": "치주", "difficulty": Difficulty.MEDIUM,
        "question_text": "치주조직에 포함되지 않는 것은?",
        "choices": ["치은", "치주인대", "백악질", "치조골", "법랑질"],
        "correct_answer": 4,
        "explanation": "치주조직 4종: 치은, 치주인대, 백악질, 치조골. 법랑질은 치아 조직.",
        "tags": ["해부", "치주조직"],
    },
    {
        "subject": "구강해부학", "unit": "타액선", "difficulty": Difficulty.MEDIUM,
        "question_text": "가장 큰 타액선은?",
        "choices": ["이하선(parotid)", "악하선", "설하선", "구순선", "구개선"],
        "correct_answer": 0,
        "explanation": "이하선이 가장 크며 장액성 분비. 악하선은 혼합성, 설하선은 점액성 우세.",
        "tags": ["해부", "타액선"],
    },
    # ============ 구강조직발생학 (6) ============
    {
        "subject": "구강조직발생학", "unit": "치아발생", "difficulty": Difficulty.MEDIUM,
        "question_text": "법랑질을 형성하는 세포는?",
        "choices": ["조골세포", "법랑모세포(ameloblast)", "상아모세포", "백악모세포", "섬유모세포"],
        "correct_answer": 1,
        "explanation": "Ameloblast가 법랑질을, odontoblast가 상아질을 형성한다.",
        "tags": ["조직", "법랑질", "발생"],
    },
    {
        "subject": "구강조직발생학", "unit": "치아발생", "difficulty": Difficulty.MEDIUM,
        "question_text": "상아질을 형성하는 세포는?",
        "choices": [
            "법랑모세포",
            "상아모세포(odontoblast)",
            "백악모세포",
            "골모세포",
            "섬유모세포",
        ],
        "correct_answer": 1,
        "explanation": "Odontoblast가 평생 일차/이차상아질을 형성하며 치수 표면에 위치.",
        "tags": ["조직", "상아질"],
    },
    {
        "subject": "구강조직발생학", "unit": "치아발생", "difficulty": Difficulty.HARD,
        "question_text": "치아 발생 단계 중 종모양 시기(bell stage)에 일어나는 일은?",
        "choices": [
            "치배 형성",
            "법랑기관과 치유두 분화",
            "법랑질 석회화 시작",
            "치근 형성",
            "맹출",
        ],
        "correct_answer": 1,
        "explanation": "Bell stage에서 법랑기관과 치유두가 명확히 분화되고 세포 분화가 시작된다.",
        "tags": ["조직", "치아발생", "Bell"],
    },
    {
        "subject": "구강조직발생학", "unit": "구강점막", "difficulty": Difficulty.MEDIUM,
        "question_text": "구강점막의 가장 두꺼운 부위는?",
        "choices": ["구강저", "협점막", "혀의 등", "경구개", "연구개"],
        "correct_answer": 3,
        "explanation": "경구개는 저작 시 압력을 견디기 위해 각화중층편평상피로 두껍다.",
        "tags": ["조직", "구강점막"],
    },
    {
        "subject": "구강조직발생학", "unit": "치아구조", "difficulty": Difficulty.MEDIUM,
        "question_text": "치아의 4대 경조직이 아닌 것은?",
        "choices": ["법랑질", "상아질", "백악질", "치조골", "치수"],
        "correct_answer": 4,
        "explanation": "치수(pulp)는 연조직. 4대 경조직: 법랑질, 상아질, 백악질, 치조골.",
        "tags": ["조직", "치아구조"],
    },
    {
        "subject": "구강조직발생학", "unit": "맹출", "difficulty": Difficulty.MEDIUM,
        "question_text": "유치 첫 맹출 시기는?",
        "choices": ["3개월", "6개월", "12개월", "18개월", "24개월"],
        "correct_answer": 1,
        "explanation": "보통 6개월경 하악 유중절치부터 맹출.",
        "tags": ["조직", "맹출", "유치"],
    },
    # ============ 구강병리학 (8) ============
    {
        "subject": "구강병리학", "unit": "치아우식", "difficulty": Difficulty.MEDIUM,
        "question_text": "치아우식의 주요 원인균은?",
        "choices": [
            "Lactobacillus",
            "Streptococcus mutans",
            "Actinomyces",
            "Porphyromonas gingivalis",
            "Treponema",
        ],
        "correct_answer": 1,
        "explanation": "S. mutans가 치아우식의 가장 중요한 원인균.",
        "tags": ["병리", "우식", "S.mutans"],
    },
    {
        "subject": "구강병리학", "unit": "치아우식", "difficulty": Difficulty.MEDIUM,
        "question_text": "치아우식 발생의 4대 요인이 아닌 것은?",
        "choices": ["치아", "세균", "기질(당분)", "시간", "유전자"],
        "correct_answer": 4,
        "explanation": "Keyes의 4요인: 치아, 세균, 기질, 시간.",
        "tags": ["병리", "우식", "Keyes"],
    },
    {
        "subject": "구강병리학", "unit": "치주", "difficulty": Difficulty.MEDIUM,
        "question_text": "만성치주염의 주요 원인균은?",
        "choices": [
            "Streptococcus mutans",
            "Porphyromonas gingivalis",
            "Lactobacillus",
            "Candida",
            "Staphylococcus aureus",
        ],
        "correct_answer": 1,
        "explanation": "P. gingivalis가 만성치주염의 대표 원인균(red complex).",
        "tags": ["병리", "치주염"],
    },
    {
        "subject": "구강병리학", "unit": "구강암", "difficulty": Difficulty.HARD,
        "question_text": "구강암 중 가장 흔한 조직학적 형태는?",
        "choices": [
            "선암",
            "편평상피세포암(SCC)",
            "기저세포암",
            "흑색종",
            "림프종",
        ],
        "correct_answer": 1,
        "explanation": "구강암의 90% 이상이 SCC. 흡연/음주가 주요 위험인자.",
        "tags": ["병리", "구강암", "SCC"],
    },
    {
        "subject": "구강병리학", "unit": "감염", "difficulty": Difficulty.MEDIUM,
        "question_text": "구강 칸디다증(아구창)의 원인은?",
        "choices": [
            "세균",
            "진균(Candida albicans)",
            "바이러스",
            "기생충",
            "알레르기",
        ],
        "correct_answer": 1,
        "explanation": "Candida albicans 감염. 면역억제 환자에서 흔하며 의치 사용자도 위험군.",
        "tags": ["병리", "칸디다", "진균"],
    },
    {
        "subject": "구강병리학", "unit": "낭종", "difficulty": Difficulty.HARD,
        "question_text": "치근단부에 발생하는 가장 흔한 치성낭종은?",
        "choices": [
            "치근단낭종(radicular cyst)",
            "함치성낭종",
            "잔류낭종",
            "각화낭종",
            "비치성낭종",
        ],
        "correct_answer": 0,
        "explanation": "치근단낭종이 가장 흔하며 만성 치근단염에서 발생.",
        "tags": ["병리", "낭종"],
    },
    {
        "subject": "구강병리학", "unit": "백반증", "difficulty": Difficulty.MEDIUM,
        "question_text": "구강 백반증(leukoplakia)의 임상적 의미는?",
        "choices": [
            "정상 변이",
            "전암병변(potentially malignant)",
            "감염성 병변",
            "외상성 병변",
            "선천성 병변",
        ],
        "correct_answer": 1,
        "explanation": "백반증은 전암병변으로 추적 관찰과 생검이 필요.",
        "tags": ["병리", "백반증", "전암"],
    },
    {
        "subject": "구강병리학", "unit": "헤르페스", "difficulty": Difficulty.MEDIUM,
        "question_text": "구순 헤르페스의 원인 바이러스는?",
        "choices": ["HSV-1", "HSV-2", "VZV", "EBV", "CMV"],
        "correct_answer": 0,
        "explanation": "단순포진 바이러스 1형(HSV-1)이 대부분의 구순 헤르페스를 일으킴.",
        "tags": ["병리", "헤르페스", "HSV"],
    },
    # ============ 구강위생학 (12) ============
    {
        "subject": "구강위생학", "unit": "잇솔질", "difficulty": Difficulty.EASY,
        "question_text": "성인에게 권장되는 잇솔질 방법은?",
        "choices": [
            "횡마법(scrub)",
            "회전법(rolling)",
            "바스법(Bass)",
            "차터법",
            "스틸만법",
        ],
        "correct_answer": 2,
        "explanation": "Bass법은 칫솔모를 치은 열구에 45도로 향하게 하여 진동시키는 방법으로 성인에게 가장 효과적.",
        "tags": ["위생", "잇솔질", "Bass"],
    },
    {
        "subject": "구강위생학", "unit": "잇솔질", "difficulty": Difficulty.MEDIUM,
        "question_text": "어린이에게 권장되는 잇솔질 방법은?",
        "choices": [
            "Bass법",
            "회전법(rolling)",
            "Stillman법",
            "차터법",
            "Fones법",
        ],
        "correct_answer": 4,
        "explanation": "Fones법은 원형으로 닦는 방법으로 손기술이 부족한 어린이에게 적합.",
        "tags": ["위생", "잇솔질", "Fones"],
    },
    {
        "subject": "구강위생학", "unit": "치간세정", "difficulty": Difficulty.MEDIUM,
        "question_text": "치실 사용의 주요 목적은?",
        "choices": [
            "치아 미백",
            "구취 제거",
            "치간 세정과 치은연하 plaque 제거",
            "치아 색조 변화",
            "잇몸 마사지만",
        ],
        "correct_answer": 2,
        "explanation": "치실은 칫솔이 닿지 않는 인접면 plaque를 제거.",
        "tags": ["위생", "치실"],
    },
    {
        "subject": "구강위생학", "unit": "구강세척제", "difficulty": Difficulty.MEDIUM,
        "question_text": "치과에서 가장 효과적인 항플라크 효과를 가진 구강세척제 성분은?",
        "choices": [
            "에탄올",
            "클로르헥시딘(chlorhexidine)",
            "불소",
            "자일리톨",
            "베이킹소다",
        ],
        "correct_answer": 1,
        "explanation": "0.12% 클로르헥시딘이 가장 강력한 항plaque 효과. 단, 장기 사용 시 착색.",
        "tags": ["위생", "클로르헥시딘"],
    },
    {
        "subject": "구강위생학", "unit": "잇솔", "difficulty": Difficulty.EASY,
        "question_text": "칫솔모의 적절한 강도는?",
        "choices": ["부드러운", "중간", "단단한", "매우 단단한", "철제"],
        "correct_answer": 0,
        "explanation": "부드러운 칫솔모가 잇몸 손상을 줄이고 충분한 청결 효과를 낸다.",
        "tags": ["위생", "칫솔"],
    },
    {
        "subject": "구강위생학", "unit": "잇솔교환", "difficulty": Difficulty.EASY,
        "question_text": "칫솔 교환 권장 주기는?",
        "choices": ["1주", "1개월", "3개월", "6개월", "12개월"],
        "correct_answer": 2,
        "explanation": "3개월 또는 칫솔모가 벌어지면 즉시 교체.",
        "tags": ["위생", "칫솔교환"],
    },
    {
        "subject": "구강위생학", "unit": "구취", "difficulty": Difficulty.MEDIUM,
        "question_text": "구취의 가장 흔한 원인 부위는?",
        "choices": ["위장", "혀의 후방", "치아 우식", "잇몸 출혈", "타액선"],
        "correct_answer": 1,
        "explanation": "혀 뒤쪽의 설태(tongue coating)가 휘발성 황화합물을 가장 많이 생성.",
        "tags": ["위생", "구취"],
    },
    {
        "subject": "구강위생학", "unit": "의치관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "총의치 사용자에게 권장되는 의치 관리법은?",
        "choices": [
            "끓는 물로 소독",
            "부드러운 솔로 매일 닦고 야간에 물에 담그기",
            "치약 사용 금지",
            "햇빛에 말리기",
            "1주에 한 번만 세척",
        ],
        "correct_answer": 1,
        "explanation": "부드러운 의치솔로 매일 세척, 야간에는 변형 방지를 위해 물이나 세정액에 담가 보관.",
        "tags": ["위생", "의치"],
    },
    {
        "subject": "구강위생학", "unit": "보철물", "difficulty": Difficulty.MEDIUM,
        "question_text": "임플란트 환자에게 적합한 치간 청결도구는?",
        "choices": [
            "일반 치실",
            "치간칫솔(interdental brush)",
            "이쑤시개",
            "철사",
            "거즈",
        ],
        "correct_answer": 1,
        "explanation": "임플란트 주위염 예방을 위해 치간칫솔과 임플란트 전용 치실을 권장.",
        "tags": ["위생", "임플란트"],
    },
    {
        "subject": "구강위생학", "unit": "교육", "difficulty": Difficulty.MEDIUM,
        "question_text": "구강보건교육 시 가장 효과적인 방법은?",
        "choices": [
            "강의식 일방 전달",
            "시청각 자료 + 시범 + 실습",
            "유인물만 배포",
            "온라인 교육만",
            "검사만",
        ],
        "correct_answer": 1,
        "explanation": "다감각 자극과 직접 실습이 가장 학습 효과가 높다.",
        "tags": ["위생", "교육"],
    },
    {
        "subject": "구강위생학", "unit": "특수환자", "difficulty": Difficulty.HARD,
        "question_text": "지체장애 환자 구강관리의 핵심은?",
        "choices": [
            "장애 정도에 관계없이 동일하게",
            "환자의 능력에 맞춘 보조도구와 보호자 교육",
            "전문가만 수행",
            "일주일에 한 번",
            "구강세척제만",
        ],
        "correct_answer": 1,
        "explanation": "특수칫솔, 손잡이 보조 등으로 환자 자립을 돕고 보호자가 보완.",
        "tags": ["위생", "장애인"],
    },
    {
        "subject": "구강위생학", "unit": "임산부", "difficulty": Difficulty.MEDIUM,
        "question_text": "임신 중 치과 치료에 가장 안전한 시기는?",
        "choices": ["임신 1기(1~3개월)", "임신 2기(4~6개월)", "임신 3기(7~9개월)", "출산 직전", "수유 중"],
        "correct_answer": 1,
        "explanation": "임신 2기(2nd trimester)가 가장 안전. 1기는 기관형성기, 3기는 자세 부담.",
        "tags": ["위생", "임산부"],
    },
    # ============ 치주관리학 (10) ============
    {
        "subject": "치주관리학", "unit": "치은", "difficulty": Difficulty.MEDIUM,
        "question_text": "건강한 치은의 색은?",
        "choices": ["선홍색", "암적색", "분홍색(coral pink)", "흰색", "보라색"],
        "correct_answer": 2,
        "explanation": "건강한 치은은 corral pink, 점점이 stippling이 보임.",
        "tags": ["치주", "치은"],
    },
    {
        "subject": "치주관리학", "unit": "치주낭", "difficulty": Difficulty.MEDIUM,
        "question_text": "정상 치은열구의 깊이는?",
        "choices": ["1~3 mm", "4~5 mm", "6~7 mm", "8 mm 이상", "0 mm"],
        "correct_answer": 0,
        "explanation": "정상은 1~3 mm. 4 mm 이상은 치주낭으로 분류.",
        "tags": ["치주", "치주낭"],
    },
    {
        "subject": "치주관리학", "unit": "스케일링", "difficulty": Difficulty.MEDIUM,
        "question_text": "치석 제거(scaling)의 주요 목적은?",
        "choices": [
            "미백",
            "치아 평활화",
            "plaque/calculus 제거로 치주염 예방",
            "치아 색 변경",
            "치통 제거",
        ],
        "correct_answer": 2,
        "explanation": "스케일링은 치주염 예방의 가장 기본적이고 핵심적 처치.",
        "tags": ["치주", "스케일링"],
    },
    {
        "subject": "치주관리학", "unit": "스케일링", "difficulty": Difficulty.MEDIUM,
        "question_text": "초음파 스케일러의 금기증은?",
        "choices": [
            "치석 환자",
            "심장박동기 사용자(일부 종류)",
            "건강한 잇몸",
            "치아 우식",
            "구강 건조증",
        ],
        "correct_answer": 1,
        "explanation": "구식 단극성 박동기는 초음파 간섭 우려. 최신 박동기는 대부분 안전하나 의사 확인 필요.",
        "tags": ["치주", "스케일링", "박동기"],
    },
    {
        "subject": "치주관리학", "unit": "치은염", "difficulty": Difficulty.MEDIUM,
        "question_text": "치은염의 가장 흔한 임상 증상은?",
        "choices": [
            "치아 흔들림",
            "치은 출혈",
            "치아 탈락",
            "심한 통증",
            "치은 퇴축",
        ],
        "correct_answer": 1,
        "explanation": "잇솔질 시 출혈이 치은염의 첫 신호. 치은염은 가역적, 치주염은 비가역적.",
        "tags": ["치주", "치은염"],
    },
    {
        "subject": "치주관리학", "unit": "치주염", "difficulty": Difficulty.HARD,
        "question_text": "만성 치주염과 치은염의 가장 중요한 차이는?",
        "choices": [
            "통증 유무",
            "출혈 유무",
            "치조골 흡수 여부",
            "치아 색",
            "구취",
        ],
        "correct_answer": 2,
        "explanation": "치주염은 부착소실(attachment loss)과 치조골 흡수가 동반된다.",
        "tags": ["치주", "치주염", "감별"],
    },
    {
        "subject": "치주관리학", "unit": "치주낭측정", "difficulty": Difficulty.MEDIUM,
        "question_text": "치주낭 측정 시 사용하는 도구는?",
        "choices": [
            "explorer",
            "periodontal probe",
            "scaler",
            "curet",
            "mirror",
        ],
        "correct_answer": 1,
        "explanation": "치주탐침(periodontal probe)으로 부드럽게 0.25N 정도의 힘으로 측정.",
        "tags": ["치주", "치주탐침"],
    },
    {
        "subject": "치주관리학", "unit": "유지관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "치주 치료 후 유지관리(SPT) 권장 간격은?",
        "choices": ["1개월", "3개월", "6개월", "1년", "2년"],
        "correct_answer": 1,
        "explanation": "일반적으로 3개월 간격이 표준 SPT. 위험도에 따라 조정.",
        "tags": ["치주", "유지관리", "SPT"],
    },
    {
        "subject": "치주관리학", "unit": "위험요인", "difficulty": Difficulty.MEDIUM,
        "question_text": "치주염의 위험요인이 아닌 것은?",
        "choices": ["흡연", "당뇨", "스트레스", "유전", "고섬유 식이"],
        "correct_answer": 4,
        "explanation": "고섬유 식이는 위험요인이 아닌 보호 요인.",
        "tags": ["치주", "위험요인"],
    },
    {
        "subject": "치주관리학", "unit": "수기구", "difficulty": Difficulty.HARD,
        "question_text": "치은연하 치석 제거에 가장 적합한 수기구는?",
        "choices": [
            "Sickle scaler",
            "Universal curet",
            "Gracey curet",
            "Hoe",
            "File",
        ],
        "correct_answer": 2,
        "explanation": "Gracey curet는 치은연하 치석/괴사 백악질 제거에 가장 적합 (치아별 부위 특이성).",
        "tags": ["치주", "Gracey", "수기구"],
    },
    # ============ 예방치과학 (10) ============
    {
        "subject": "예방치과학", "unit": "불소", "difficulty": Difficulty.MEDIUM,
        "question_text": "불소도포의 주요 작용 기전은?",
        "choices": [
            "치아 색 변화",
            "법랑질 결정의 산 저항성 증가",
            "통증 감소",
            "치석 용해",
            "치은 마사지",
        ],
        "correct_answer": 1,
        "explanation": "불소는 hydroxyapatite를 fluorapatite로 전환시켜 산 저항성을 높이고 재광화를 촉진.",
        "tags": ["예방", "불소"],
    },
    {
        "subject": "예방치과학", "unit": "불소", "difficulty": Difficulty.MEDIUM,
        "question_text": "수돗물 불소화 농도로 권장되는 수치는?",
        "choices": ["0.1 ppm", "0.5 ppm", "0.7~1.0 ppm", "5 ppm", "10 ppm"],
        "correct_answer": 2,
        "explanation": "WHO 권장 0.7~1.0 ppm. 너무 높으면 반상치 위험.",
        "tags": ["예방", "수돗물불소화"],
    },
    {
        "subject": "예방치과학", "unit": "치면열구전색", "difficulty": Difficulty.MEDIUM,
        "question_text": "치면열구전색(sealant)의 주된 적용 부위는?",
        "choices": [
            "전치 순면",
            "구치 교합면의 소와열구",
            "전치 인접면",
            "치근",
            "치은",
        ],
        "correct_answer": 1,
        "explanation": "구치부 교합면 소와열구는 치아우식 호발 부위로 전색 효과가 큼.",
        "tags": ["예방", "전색", "sealant"],
    },
    {
        "subject": "예방치과학", "unit": "식이", "difficulty": Difficulty.MEDIUM,
        "question_text": "치아우식 발생 위험이 가장 높은 음식 형태는?",
        "choices": [
            "단단한 음식",
            "물",
            "끈적이는 단 음식",
            "생야채",
            "고기",
        ],
        "correct_answer": 2,
        "explanation": "끈적이는 단 음식(캐러멜, 사탕)은 치면 잔류 시간이 길어 우식 위험이 가장 큼.",
        "tags": ["예방", "식이", "우식"],
    },
    {
        "subject": "예방치과학", "unit": "식이", "difficulty": Difficulty.MEDIUM,
        "question_text": "자일리톨이 치아우식 예방에 효과적인 이유는?",
        "choices": [
            "당이 없어서",
            "S. mutans가 자일리톨을 대사하지 못함",
            "타액 분비 억제",
            "치아 미백 효과",
            "산성 환경 형성",
        ],
        "correct_answer": 1,
        "explanation": "자일리톨은 5탄당으로 S. mutans가 대사할 수 없어 산을 만들지 못한다.",
        "tags": ["예방", "자일리톨"],
    },
    {
        "subject": "예방치과학", "unit": "구강위생지수", "difficulty": Difficulty.MEDIUM,
        "question_text": "OHI-S(간이구강위생지수)의 구성요소는?",
        "choices": [
            "DI-S + CI-S",
            "PI + GI",
            "CPI + CPITN",
            "DMFT + DMFS",
            "DI + GI",
        ],
        "correct_answer": 0,
        "explanation": "OHI-S = Debris Index Simplified + Calculus Index Simplified.",
        "tags": ["예방", "OHI-S"],
    },
    {
        "subject": "예방치과학", "unit": "지수", "difficulty": Difficulty.HARD,
        "question_text": "DMFT 지수에서 'F'가 의미하는 것은?",
        "choices": ["Fissure", "Filled(충전된 치아)", "Fluoride", "Fracture", "Free"],
        "correct_answer": 1,
        "explanation": "D=Decayed, M=Missing, F=Filled, T=Teeth.",
        "tags": ["예방", "DMFT"],
    },
    {
        "subject": "예방치과학", "unit": "교육", "difficulty": Difficulty.MEDIUM,
        "question_text": "유치원생 구강보건 교육의 중점은?",
        "choices": [
            "치주염 예방",
            "잇솔질 습관 형성과 단 음식 줄이기",
            "임플란트 관리",
            "교정 치료",
            "보철물 관리",
        ],
        "correct_answer": 1,
        "explanation": "유치원생은 잇솔질 습관 형성과 식이 교육이 가장 중요.",
        "tags": ["예방", "교육", "어린이"],
    },
    {
        "subject": "예방치과학", "unit": "임산부", "difficulty": Difficulty.MEDIUM,
        "question_text": "임산부에게 자주 발생하는 치주질환은?",
        "choices": [
            "치주염",
            "임신성 치은염",
            "치근단염",
            "구내염",
            "치아우식",
        ],
        "correct_answer": 1,
        "explanation": "호르몬 변화로 임신성 치은염이 흔하며 분만 후 호전.",
        "tags": ["예방", "임산부", "치은염"],
    },
    {
        "subject": "예방치과학", "unit": "검진", "difficulty": Difficulty.EASY,
        "question_text": "정기 구강검진의 권장 주기는?",
        "choices": ["1주일", "1개월", "6개월", "2년", "5년"],
        "correct_answer": 2,
        "explanation": "6개월마다 정기 구강검진 권장.",
        "tags": ["예방", "검진"],
    },
    # ============ 의료법규 (6) ============
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.MEDIUM,
        "question_text": "치과위생사의 면허 발급 기관은?",
        "choices": ["치과의사협회", "보건복지부장관", "교육부장관", "병원장", "지자체"],
        "correct_answer": 1,
        "explanation": "의료기사 면허는 보건복지부장관 발급.",
        "tags": ["법규", "면허"],
    },
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.MEDIUM,
        "question_text": "치과위생사의 업무 지도자는?",
        "choices": ["의사", "치과의사", "간호사", "약사", "물리치료사"],
        "correct_answer": 1,
        "explanation": "치과위생사는 치과의사의 지도 아래 업무를 수행한다.",
        "tags": ["법규", "업무"],
    },
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.MEDIUM,
        "question_text": "치과위생사의 업무 범위에 해당하지 않는 것은?",
        "choices": [
            "치아 및 구강질환의 예방",
            "구강보건교육",
            "치석 제거(치과의사 지도하)",
            "구강병의 진단",
            "치아 본뜨기 보조",
        ],
        "correct_answer": 3,
        "explanation": "진단은 치과의사의 고유 업무. 치과위생사는 보조와 예방 업무.",
        "tags": ["법규", "업무범위"],
    },
    {
        "subject": "의료법규", "unit": "감염병예방법", "difficulty": Difficulty.MEDIUM,
        "question_text": "치과 진료실의 표준주의 원칙으로 옳은 것은?",
        "choices": [
            "감염 환자만 격리",
            "모든 환자의 혈액·체액을 잠재적 감염원으로 간주",
            "장갑만 착용",
            "마스크만 착용",
            "필요할 때만 손씻기",
        ],
        "correct_answer": 1,
        "explanation": "표준주의는 모든 환자에게 적용되는 가장 기본 원칙.",
        "tags": ["법규", "표준주의"],
    },
    {
        "subject": "의료법규", "unit": "의료법", "difficulty": Difficulty.MEDIUM,
        "question_text": "의료인이 비밀 누설 금지 위반 시 처벌은?",
        "choices": [
            "벌금",
            "징역 또는 벌금",
            "면허 취소",
            "경고",
            "처벌 없음",
        ],
        "correct_answer": 1,
        "explanation": "의료법상 비밀누설은 형사 처벌(징역 또는 벌금) 대상.",
        "tags": ["법규", "비밀유지"],
    },
    {
        "subject": "의료법규", "unit": "구강보건법", "difficulty": Difficulty.HARD,
        "question_text": "구강보건법의 목적은?",
        "choices": [
            "치과의사 양성",
            "국민의 구강보건 향상과 건강 증진",
            "치과 산업 진흥",
            "의료기관 평가",
            "치과 보험 관리",
        ],
        "correct_answer": 1,
        "explanation": "구강보건법은 국민의 구강보건 향상과 건강 증진이 목적.",
        "tags": ["법규", "구강보건법"],
    },
]
