"""간호학과 시드 문제 (80문항).

성인간호학 25 / 모성간호학 12 / 아동간호학 12 / 정신간호학 10 /
지역사회간호학 10 / 기본간호학 6 / 보건의약관계법규 5
"""

from app.models.enums import Department, Difficulty, QuestionType

DEPT = Department.NURSING
TYPE = QuestionType.SINGLE_CHOICE
SOURCE = "샘플 시드 (Day 3)"

NURSING_QUESTIONS = [
    # ============ 성인간호학 (25) ============
    {
        "subject": "성인간호학", "unit": "심혈관계", "difficulty": Difficulty.MEDIUM,
        "question_text": "심방세동(atrial fibrillation) 환자의 가장 중요한 합병증은?",
        "choices": ["폐색전증", "뇌졸중", "심근염", "심낭염", "심장막삼출"],
        "correct_answer": 1,
        "explanation": "심방세동은 심방 내 혈전 형성으로 색전성 뇌졸중의 위험을 크게 증가시킨다. 항응고요법이 필수.",
        "tags": ["심혈관계", "부정맥", "합병증"],
    },
    {
        "subject": "성인간호학", "unit": "심혈관계", "difficulty": Difficulty.HARD,
        "question_text": "급성 심근경색증 환자에게 우선적으로 투여하는 약물이 아닌 것은?",
        "choices": ["산소", "아스피린", "니트로글리세린", "베타차단제", "와파린"],
        "correct_answer": 4,
        "explanation": "MONA(Morphine, Oxygen, Nitroglycerin, Aspirin)가 초기 처치의 기본. 와파린은 장기 항응고제로 급성기에는 사용하지 않는다.",
        "tags": ["심혈관계", "AMI", "응급간호"],
    },
    {
        "subject": "성인간호학", "unit": "심혈관계", "difficulty": Difficulty.EASY,
        "question_text": "정상 성인의 안정시 평균 수축기 혈압 범위는?",
        "choices": ["80~99 mmHg", "100~119 mmHg", "120~129 mmHg", "130~139 mmHg", "140~159 mmHg"],
        "correct_answer": 1,
        "explanation": "정상 혈압은 수축기 120 미만, 이완기 80 미만. 100~119가 정상 범위 내에 해당.",
        "tags": ["혈압", "활력징후"],
    },
    {
        "subject": "성인간호학", "unit": "호흡기계", "difficulty": Difficulty.MEDIUM,
        "question_text": "만성폐쇄성폐질환(COPD) 환자에게 산소요법 시 주의해야 할 점은?",
        "choices": [
            "고농도 산소를 빠르게 투여한다",
            "산소 농도를 점차 증가시킨다",
            "저농도(1~3L/min) 산소를 투여한다",
            "100% 산소를 투여한다",
            "산소를 투여하지 않는다",
        ],
        "correct_answer": 2,
        "explanation": "COPD 환자는 만성적인 고탄산혈증으로 호흡중추가 저산소에 의존하므로, 고농도 산소는 호흡억제를 유발할 수 있다.",
        "tags": ["호흡기계", "COPD", "산소요법"],
    },
    {
        "subject": "성인간호학", "unit": "호흡기계", "difficulty": Difficulty.MEDIUM,
        "question_text": "결핵 환자 격리 시 사용하는 마스크는?",
        "choices": ["일반 마스크", "수술용 마스크", "N95 마스크", "면 마스크", "투명 안면보호구"],
        "correct_answer": 2,
        "explanation": "결핵은 비말핵을 통한 공기전파이므로 N95 이상의 호흡기 보호구가 필요하다.",
        "tags": ["호흡기계", "결핵", "감염관리"],
    },
    {
        "subject": "성인간호학", "unit": "호흡기계", "difficulty": Difficulty.HARD,
        "question_text": "기관내삽관 환자의 합병증을 예방하기 위한 가장 중요한 간호중재는?",
        "choices": [
            "체위 변경을 자주한다",
            "구강간호를 자주한다",
            "흡인을 자주한다",
            "수액을 충분히 공급한다",
            "진정제를 사용한다",
        ],
        "correct_answer": 1,
        "explanation": "VAP(인공호흡기 관련 폐렴) 예방의 핵심은 클로르헥시딘 구강간호와 두부거상 30~45도 유지.",
        "tags": ["호흡기계", "기관삽관", "VAP"],
    },
    {
        "subject": "성인간호학", "unit": "소화기계", "difficulty": Difficulty.MEDIUM,
        "question_text": "위내시경 검사 후 가장 먼저 확인해야 할 것은?",
        "choices": ["출혈 여부", "구토반사 회복", "복통 여부", "혈압", "활력징후"],
        "correct_answer": 1,
        "explanation": "국소마취로 인해 일시적으로 구토반사가 소실되므로 흡인 위험이 있다. 구토반사 회복을 확인한 후 음식 섭취 가능.",
        "tags": ["소화기계", "내시경", "검사후간호"],
    },
    {
        "subject": "성인간호학", "unit": "소화기계", "difficulty": Difficulty.MEDIUM,
        "question_text": "간경변증 환자에게 식이로 제한해야 할 영양소는?",
        "choices": ["탄수화물", "지방", "단백질(간성혼수 시)", "비타민", "식이섬유"],
        "correct_answer": 2,
        "explanation": "간성혼수가 발생하면 암모니아 생성을 줄이기 위해 단백질 섭취를 제한한다.",
        "tags": ["소화기계", "간경변", "영양"],
    },
    {
        "subject": "성인간호학", "unit": "내분비계", "difficulty": Difficulty.MEDIUM,
        "question_text": "당뇨병 환자의 저혈당 증상이 아닌 것은?",
        "choices": ["발한", "떨림", "심계항진", "다뇨", "혼동"],
        "correct_answer": 3,
        "explanation": "다뇨(polyuria)는 고혈당의 대표 증상. 저혈당은 자율신경 항진(발한, 떨림, 심계항진)과 신경학적 증상(혼동, 의식저하).",
        "tags": ["내분비", "당뇨", "저혈당"],
    },
    {
        "subject": "성인간호학", "unit": "내분비계", "difficulty": Difficulty.EASY,
        "question_text": "1형 당뇨병의 가장 적절한 치료법은?",
        "choices": ["식이요법만", "운동요법만", "경구혈당강하제", "인슐린 주사", "한약 복용"],
        "correct_answer": 3,
        "explanation": "1형 당뇨병은 췌장 베타세포가 파괴되어 인슐린 분비가 거의 없으므로 인슐린 보충이 필수.",
        "tags": ["내분비", "당뇨", "인슐린"],
    },
    {
        "subject": "성인간호학", "unit": "신장계", "difficulty": Difficulty.MEDIUM,
        "question_text": "혈액투석 환자의 동정맥루(AV fistula) 관리로 옳지 않은 것은?",
        "choices": [
            "수술한 팔에서 혈압측정을 하지 않는다",
            "수술한 팔에서 채혈하지 않는다",
            "매일 진동(thrill)을 확인한다",
            "수술한 팔에 무거운 것을 들지 않게 한다",
            "수술 직후 즉시 사용한다",
        ],
        "correct_answer": 4,
        "explanation": "AV fistula는 성숙(maturation)에 보통 4~6주가 필요하며, 그 전에는 사용할 수 없다.",
        "tags": ["신장", "혈액투석", "AVF"],
    },
    {
        "subject": "성인간호학", "unit": "신장계", "difficulty": Difficulty.HARD,
        "question_text": "급성신부전의 핍뇨기 환자에게 가장 위험한 전해질 불균형은?",
        "choices": ["저칼륨혈증", "고칼륨혈증", "저나트륨혈증", "고칼슘혈증", "저마그네슘혈증"],
        "correct_answer": 1,
        "explanation": "신장 배설 저하로 고칼륨혈증이 발생하며, 치명적인 부정맥(심정지)을 유발할 수 있다.",
        "tags": ["신장", "급성신부전", "전해질"],
    },
    {
        "subject": "성인간호학", "unit": "근골격계", "difficulty": Difficulty.MEDIUM,
        "question_text": "석고붕대(cast)를 적용한 환자의 가장 중요한 사정 항목은?",
        "choices": ["체온", "5P(통증, 창백, 맥박소실, 감각이상, 마비)", "혈압", "호흡수", "소변량"],
        "correct_answer": 1,
        "explanation": "구획증후군(Compartment syndrome)을 조기 발견하기 위해 5P를 정기적으로 사정한다.",
        "tags": ["근골격계", "석고붕대", "5P"],
    },
    {
        "subject": "성인간호학", "unit": "근골격계", "difficulty": Difficulty.MEDIUM,
        "question_text": "고관절 전치환술(THR) 후 탈구 예방을 위한 자세는?",
        "choices": [
            "다리 모음",
            "다리 외전 유지",
            "고관절 90도 이상 굴곡",
            "다리 내회전",
            "엎드린 자세",
        ],
        "correct_answer": 1,
        "explanation": "외전(abduction)을 유지하고 90도 이상 굴곡, 내회전, 내전을 피해야 한다.",
        "tags": ["근골격계", "고관절", "THR"],
    },
    {
        "subject": "성인간호학", "unit": "신경계", "difficulty": Difficulty.HARD,
        "question_text": "두개내압(ICP) 상승 환자의 우선 간호중재는?",
        "choices": [
            "두부 거상 30도",
            "트렌델렌버그 자세",
            "엎드린 자세",
            "측위",
            "앉은 자세",
        ],
        "correct_answer": 0,
        "explanation": "두부거상 15~30도는 정맥 환류를 촉진하여 ICP를 낮춘다.",
        "tags": ["신경계", "ICP", "두부손상"],
    },
    {
        "subject": "성인간호학", "unit": "신경계", "difficulty": Difficulty.MEDIUM,
        "question_text": "글래스고우 혼수척도(GCS)에서 평가하지 않는 항목은?",
        "choices": ["눈뜨기", "언어반응", "운동반응", "동공반사", "(없음)"],
        "correct_answer": 3,
        "explanation": "GCS는 눈뜨기(E), 언어반응(V), 운동반응(M)의 3가지 항목으로 구성된다.",
        "tags": ["신경계", "GCS", "의식사정"],
    },
    {
        "subject": "성인간호학", "unit": "혈액계", "difficulty": Difficulty.MEDIUM,
        "question_text": "수혈 중 환자가 오한, 발열, 두드러기를 호소할 때 가장 먼저 해야 할 행동은?",
        "choices": [
            "수혈 속도를 줄인다",
            "수혈을 즉시 중단한다",
            "해열제를 투여한다",
            "주치의에게 보고한다",
            "활력징후를 측정한다",
        ],
        "correct_answer": 1,
        "explanation": "수혈 부작용 의심 시 즉시 수혈을 중단하고 정맥로는 생리식염수로 유지한 뒤 의사에게 보고한다.",
        "tags": ["혈액", "수혈", "수혈반응"],
    },
    {
        "subject": "성인간호학", "unit": "면역계", "difficulty": Difficulty.MEDIUM,
        "question_text": "아나필락시스 쇼크 환자에게 가장 먼저 투여해야 할 약물은?",
        "choices": ["항히스타민제", "스테로이드", "에피네프린", "아드레날린 흡입제", "도파민"],
        "correct_answer": 2,
        "explanation": "에피네프린 0.3~0.5mg IM이 1차 치료. 기관지 확장과 혈관 수축을 동시에 유도한다.",
        "tags": ["면역", "아나필락시스", "응급"],
    },
    {
        "subject": "성인간호학", "unit": "암간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "항암화학요법 환자에게 가장 흔한 부작용은?",
        "choices": ["변비", "골수억제", "탈모", "구토", "피로"],
        "correct_answer": 1,
        "explanation": "항암제는 빠르게 분열하는 세포를 공격하므로 골수억제(빈혈, 백혈구 감소, 혈소판 감소)가 가장 중요한 부작용이다.",
        "tags": ["암", "항암요법", "부작용"],
    },
    {
        "subject": "성인간호학", "unit": "암간호", "difficulty": Difficulty.HARD,
        "question_text": "호중구 감소증(절대호중구수 < 500) 환자에게 가장 적절한 격리는?",
        "choices": ["접촉격리", "비말격리", "공기격리", "역격리(보호격리)", "표준주의"],
        "correct_answer": 3,
        "explanation": "면역억제 환자는 외부로부터 감염원이 들어오지 않도록 역격리(보호격리)가 필요하다.",
        "tags": ["암", "호중구감소증", "감염관리"],
    },
    {
        "subject": "성인간호학", "unit": "수술전후간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "전신마취 수술 후 가장 위험한 합병증은?",
        "choices": ["오심·구토", "기도폐쇄", "통증", "변비", "발열"],
        "correct_answer": 1,
        "explanation": "전신마취 후 의식이 완전히 회복되기 전까지 혀의 후방 처짐이나 분비물로 인한 기도폐쇄가 가장 위험하다.",
        "tags": ["수술", "마취", "회복실간호"],
    },
    {
        "subject": "성인간호학", "unit": "수술전후간호", "difficulty": Difficulty.EASY,
        "question_text": "수술 전 금식의 주된 목적은?",
        "choices": ["소화불량 예방", "구토 및 흡인 예방", "혈당 조절", "체중 감소", "피로 감소"],
        "correct_answer": 1,
        "explanation": "전신마취 시 위 내용물이 폐로 흡인되는 것을 예방하기 위해 8시간 이상 금식한다.",
        "tags": ["수술", "수술전간호", "금식"],
    },
    {
        "subject": "성인간호학", "unit": "통증관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "암성 통증의 약물 치료에서 WHO 3단계 진통제 사다리의 가장 강력한 단계는?",
        "choices": ["비마약성 진통제", "약한 마약성 진통제", "강한 마약성 진통제", "보조 진통제", "한방 치료"],
        "correct_answer": 2,
        "explanation": "WHO 사다리: 1단계 비마약성(아세트아미노펜/NSAID) → 2단계 약한 마약성(코데인) → 3단계 강한 마약성(모르핀).",
        "tags": ["통증", "암성통증", "WHO사다리"],
    },
    {
        "subject": "성인간호학", "unit": "노인간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "노인 환자 낙상 예방을 위한 가장 효과적인 중재는?",
        "choices": [
            "신체 억제대 사용",
            "환경 정비 및 야간 조명",
            "약물 진정",
            "침상 안정",
            "단독 거주",
        ],
        "correct_answer": 1,
        "explanation": "환경 정비, 미끄럼 방지, 야간 조명, 보행 보조구 등이 가장 효과적. 신체 억제대는 오히려 낙상 위험을 높일 수 있다.",
        "tags": ["노인", "낙상예방", "안전"],
    },
    {
        "subject": "성인간호학", "unit": "체액균형", "difficulty": Difficulty.HARD,
        "question_text": "고칼륨혈증 환자에게 응급으로 사용하는 약물 중 칼륨을 세포내로 이동시키는 것은?",
        "choices": ["칼슘글루코네이트", "인슐린+포도당", "이뇨제", "카요넥살레이트", "수분 제한"],
        "correct_answer": 1,
        "explanation": "인슐린은 포도당과 함께 칼륨을 세포 내로 이동시켜 일시적으로 혈청 K+를 낮춘다.",
        "tags": ["전해질", "고칼륨혈증", "응급"],
    },
    # ============ 모성간호학 (12) ============
    {
        "subject": "모성간호학", "unit": "산전관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "임신 중 가장 흔한 빈혈의 종류는?",
        "choices": ["용혈성 빈혈", "철결핍성 빈혈", "엽산결핍성 빈혈", "재생불량성 빈혈", "지중해빈혈"],
        "correct_answer": 1,
        "explanation": "임신 중 혈장량 증가와 태아의 철 요구량 증가로 철결핍성 빈혈이 가장 흔하다.",
        "tags": ["모성", "임신", "빈혈"],
    },
    {
        "subject": "모성간호학", "unit": "산전관리", "difficulty": Difficulty.EASY,
        "question_text": "임신 기간 정상 분만일은?",
        "choices": ["32주", "34주", "37~42주", "44주", "45주"],
        "correct_answer": 2,
        "explanation": "정상 임신 기간은 37~42주(만삭), 37주 미만은 조산.",
        "tags": ["모성", "분만", "임신주수"],
    },
    {
        "subject": "모성간호학", "unit": "분만", "difficulty": Difficulty.MEDIUM,
        "question_text": "분만 1기 잠재기에 가장 우선적인 간호중재는?",
        "choices": [
            "회음부 절개 준비",
            "산모 격려와 호흡법 교육",
            "옥시토신 투여",
            "제왕절개 준비",
            "신생아 처치",
        ],
        "correct_answer": 1,
        "explanation": "잠재기는 자궁경부 0~3cm 개대 단계로, 산모 교육과 정서적 지지가 핵심.",
        "tags": ["모성", "분만", "분만1기"],
    },
    {
        "subject": "모성간호학", "unit": "분만", "difficulty": Difficulty.HARD,
        "question_text": "분만 후 자궁이완으로 인한 산후출혈의 1차 중재는?",
        "choices": [
            "자궁저부 마사지",
            "옥시토신 정맥주사",
            "수혈",
            "자궁절제술",
            "수액 공급",
        ],
        "correct_answer": 0,
        "explanation": "산후출혈 시 가장 먼저 자궁저부 마사지로 자궁수축을 유도한다.",
        "tags": ["모성", "산후출혈", "응급"],
    },
    {
        "subject": "모성간호학", "unit": "산욕기", "difficulty": Difficulty.MEDIUM,
        "question_text": "산욕기 자궁퇴축이 정상적으로 이루어지는 시기는?",
        "choices": ["1주일", "2주일", "4~6주", "8주", "12주"],
        "correct_answer": 2,
        "explanation": "분만 후 4~6주에 걸쳐 자궁이 임신 전 크기로 돌아간다.",
        "tags": ["모성", "산욕기", "자궁퇴축"],
    },
    {
        "subject": "모성간호학", "unit": "산욕기", "difficulty": Difficulty.MEDIUM,
        "question_text": "모유수유의 장점으로 옳지 않은 것은?",
        "choices": [
            "아기의 면역력 증진",
            "산모의 자궁수축 촉진",
            "모자 애착 증진",
            "산모의 빠른 체중 감소",
            "산모의 유방암 위험 증가",
        ],
        "correct_answer": 4,
        "explanation": "모유수유는 산모의 유방암·난소암 위험을 오히려 감소시킨다.",
        "tags": ["모성", "모유수유", "산욕기"],
    },
    {
        "subject": "모성간호학", "unit": "임신성합병증", "difficulty": Difficulty.HARD,
        "question_text": "임신성 고혈압(preeclampsia) 환자의 가장 위험한 합병증은?",
        "choices": ["조산", "자간증(eclampsia)", "임신성 당뇨", "양수과다증", "태반조기박리"],
        "correct_answer": 1,
        "explanation": "전자간증이 진행되어 경련을 동반하면 자간증이 되며 모체와 태아 모두 생명을 위협한다.",
        "tags": ["모성", "임신중독", "전자간증"],
    },
    {
        "subject": "모성간호학", "unit": "임신성합병증", "difficulty": Difficulty.MEDIUM,
        "question_text": "임신성 당뇨 산모의 신생아에서 흔히 나타나는 합병증은?",
        "choices": ["저혈당", "고혈당", "저체온", "고체온", "탈수"],
        "correct_answer": 0,
        "explanation": "엄마의 고혈당으로 태아 인슐린이 과다 분비되어 출생 후 저혈당이 발생한다.",
        "tags": ["모성", "임신성당뇨", "신생아"],
    },
    {
        "subject": "모성간호학", "unit": "여성건강", "difficulty": Difficulty.MEDIUM,
        "question_text": "자궁경부암 선별검사로 사용되는 검사는?",
        "choices": ["조직생검", "Pap smear", "초음파", "MRI", "혈액검사"],
        "correct_answer": 1,
        "explanation": "자궁경부세포진검사(Pap smear)가 표준 선별검사. HPV 검사도 함께 활용.",
        "tags": ["모성", "자궁경부암", "선별검사"],
    },
    {
        "subject": "모성간호학", "unit": "여성건강", "difficulty": Difficulty.EASY,
        "question_text": "정상 월경주기의 평균 길이는?",
        "choices": ["7일", "14일", "21일", "28일", "45일"],
        "correct_answer": 3,
        "explanation": "평균 28일(21~35일 정상 범위).",
        "tags": ["모성", "월경", "여성생리"],
    },
    {
        "subject": "모성간호학", "unit": "피임", "difficulty": Difficulty.MEDIUM,
        "question_text": "경구피임약의 절대 금기증이 아닌 것은?",
        "choices": ["혈전 병력", "흡연하는 35세 이상 여성", "유방암", "조절되지 않는 고혈압", "20대 미혼여성"],
        "correct_answer": 4,
        "explanation": "혈전, 35세 이상 흡연자, 호르몬 의존성 암, 중증 고혈압은 금기. 20대 미혼여성은 적응증.",
        "tags": ["모성", "피임", "경구피임약"],
    },
    {
        "subject": "모성간호학", "unit": "신생아", "difficulty": Difficulty.MEDIUM,
        "question_text": "Apgar 점수 평가 항목이 아닌 것은?",
        "choices": ["심박수", "호흡노력", "근긴장도", "체온", "피부색"],
        "correct_answer": 3,
        "explanation": "APGAR: Appearance(피부색), Pulse(심박), Grimace(반사), Activity(근긴장), Respiration(호흡).",
        "tags": ["모성", "신생아", "Apgar"],
    },
    # ============ 아동간호학 (12) ============
    {
        "subject": "아동간호학", "unit": "성장발달", "difficulty": Difficulty.EASY,
        "question_text": "신생아의 정상 호흡수 범위는?",
        "choices": ["12~20회/분", "20~30회/분", "30~60회/분", "60~80회/분", "80~100회/분"],
        "correct_answer": 2,
        "explanation": "신생아 정상 호흡수는 30~60회/분.",
        "tags": ["아동", "신생아", "활력징후"],
    },
    {
        "subject": "아동간호학", "unit": "성장발달", "difficulty": Difficulty.MEDIUM,
        "question_text": "12개월 영아가 할 수 있는 가장 적절한 행동은?",
        "choices": [
            "혼자 걷기 시작",
            "달리기",
            "두 발로 점프",
            "세발자전거 타기",
            "글자 쓰기",
        ],
        "correct_answer": 0,
        "explanation": "12개월 전후로 첫 걸음. 달리기는 18개월, 점프는 24개월 경.",
        "tags": ["아동", "영아", "발달"],
    },
    {
        "subject": "아동간호학", "unit": "신생아", "difficulty": Difficulty.MEDIUM,
        "question_text": "신생아 황달 중 병리적 황달의 특징은?",
        "choices": [
            "생후 24시간 이내 발생",
            "생후 2~3일 발생",
            "1주일 후 자연 소실",
            "총빌리루빈 < 12 mg/dL",
            "수유와 무관",
        ],
        "correct_answer": 0,
        "explanation": "병리적 황달은 24시간 이내 발생하며 빌리루빈 상승이 빠르다. 생리적 황달은 2~3일에 시작.",
        "tags": ["아동", "신생아", "황달"],
    },
    {
        "subject": "아동간호학", "unit": "예방접종", "difficulty": Difficulty.MEDIUM,
        "question_text": "BCG 예방접종 시기는?",
        "choices": ["생후 4주 이내", "생후 2개월", "생후 6개월", "생후 12개월", "취학 전"],
        "correct_answer": 0,
        "explanation": "결핵 예방을 위한 BCG는 생후 4주 이내 접종 권장.",
        "tags": ["아동", "예방접종", "BCG"],
    },
    {
        "subject": "아동간호학", "unit": "호흡기", "difficulty": Difficulty.HARD,
        "question_text": "후두개염(epiglottitis) 환아에게 절대 하지 말아야 할 것은?",
        "choices": [
            "산소 공급",
            "설압자로 인후 검사",
            "기도확보 준비",
            "정맥로 확보",
            "응급실 후송",
        ],
        "correct_answer": 1,
        "explanation": "설압자로 인두를 자극하면 완전 기도폐쇄가 유발될 수 있으므로 절대 금기.",
        "tags": ["아동", "후두개염", "응급"],
    },
    {
        "subject": "아동간호학", "unit": "호흡기", "difficulty": Difficulty.MEDIUM,
        "question_text": "모세기관지염 환아에게 가장 중요한 간호는?",
        "choices": [
            "고열량 식이",
            "수분 공급과 가습",
            "기관지 확장제 투여",
            "스테로이드 투여",
            "항생제 투여",
        ],
        "correct_answer": 1,
        "explanation": "RSV 등 바이러스성으로 항생제 효과 없음. 수분 공급과 호흡기 가습이 가장 중요.",
        "tags": ["아동", "모세기관지염", "RSV"],
    },
    {
        "subject": "아동간호학", "unit": "소화기", "difficulty": Difficulty.MEDIUM,
        "question_text": "유문협착증 영아의 전형적인 증상은?",
        "choices": [
            "혈변",
            "분출성 구토(projectile vomiting)",
            "복부 팽만",
            "설사",
            "황달",
        ],
        "correct_answer": 1,
        "explanation": "수유 직후 분출성 구토와 우상복부 올리브형 종괴가 특징.",
        "tags": ["아동", "유문협착증", "구토"],
    },
    {
        "subject": "아동간호학", "unit": "소화기", "difficulty": Difficulty.HARD,
        "question_text": "장중첩증(intussusception)의 전형적인 증상은?",
        "choices": [
            "지속적 복통",
            "발작적 복통과 젤리 같은 혈변",
            "구토 없음",
            "발열",
            "황달",
        ],
        "correct_answer": 1,
        "explanation": "발작적 복통, 구토, currant jelly stool이 3대 증상.",
        "tags": ["아동", "장중첩증", "응급"],
    },
    {
        "subject": "아동간호학", "unit": "감염성질환", "difficulty": Difficulty.MEDIUM,
        "question_text": "수두(varicella)의 격리 기간은?",
        "choices": [
            "발진 시작부터 가피 형성까지",
            "발열 시작부터 해열까지",
            "발진 시작부터 발진 소실까지",
            "1주일",
            "10일",
        ],
        "correct_answer": 0,
        "explanation": "모든 수포가 가피로 변할 때까지 격리해야 한다 (보통 5~7일).",
        "tags": ["아동", "수두", "감염격리"],
    },
    {
        "subject": "아동간호학", "unit": "심혈관", "difficulty": Difficulty.MEDIUM,
        "question_text": "선천성 심질환 중 청색증을 동반하는 것은?",
        "choices": ["심방중격결손증(ASD)", "심실중격결손증(VSD)", "동맥관개존증(PDA)", "팔로 4징(TOF)", "대동맥축착증"],
        "correct_answer": 3,
        "explanation": "팔로 4징은 우→좌 단락으로 청색증을 유발하는 대표 질환.",
        "tags": ["아동", "선천심질환", "청색증"],
    },
    {
        "subject": "아동간호학", "unit": "혈액", "difficulty": Difficulty.MEDIUM,
        "question_text": "소아 백혈병에서 가장 흔한 형은?",
        "choices": ["급성 골수성 백혈병", "급성 림프구성 백혈병(ALL)", "만성 골수성 백혈병", "만성 림프구성 백혈병", "다발골수종"],
        "correct_answer": 1,
        "explanation": "소아 백혈병의 약 75%가 ALL.",
        "tags": ["아동", "백혈병", "ALL"],
    },
    {
        "subject": "아동간호학", "unit": "탈수", "difficulty": Difficulty.HARD,
        "question_text": "심한 탈수 영아의 수액 치료 시 가장 우선적으로 사용하는 수액은?",
        "choices": ["5% 포도당", "0.45% 식염수", "생리식염수", "5% 알부민", "수돗물"],
        "correct_answer": 2,
        "explanation": "심한 탈수의 응급 처치는 등장성 생리식염수(N/S) 20mL/kg 빠른 정주.",
        "tags": ["아동", "탈수", "수액치료"],
    },
    # ============ 정신간호학 (10) ============
    {
        "subject": "정신간호학", "unit": "조현병", "difficulty": Difficulty.MEDIUM,
        "question_text": "조현병의 음성증상에 해당하는 것은?",
        "choices": ["환청", "망상", "와해된 언어", "정서적 둔마", "긴장증적 행동"],
        "correct_answer": 3,
        "explanation": "음성증상: 정서둔마, 무의욕, 사회위축, 무쾌감. 양성증상: 환청, 망상, 와해된 언어/행동.",
        "tags": ["정신", "조현병", "음성증상"],
    },
    {
        "subject": "정신간호학", "unit": "우울증", "difficulty": Difficulty.MEDIUM,
        "question_text": "우울증 환자에게 가장 우선적으로 평가해야 할 항목은?",
        "choices": ["식욕", "수면", "자살사고", "활동량", "체중"],
        "correct_answer": 2,
        "explanation": "자살 위험성 평가가 항상 최우선. 자살사고 → 계획 → 수단의 단계적 사정 필요.",
        "tags": ["정신", "우울", "자살사정"],
    },
    {
        "subject": "정신간호학", "unit": "불안장애", "difficulty": Difficulty.MEDIUM,
        "question_text": "공황발작 환자에게 가장 효과적인 간호중재는?",
        "choices": [
            "혼자 두기",
            "조용하고 안전한 환경 제공",
            "강하게 자극",
            "운동 권유",
            "외출 권유",
        ],
        "correct_answer": 1,
        "explanation": "조용하고 안전한 환경에서 차분한 목소리로 안심시키고 호흡 조절을 돕는다.",
        "tags": ["정신", "공황장애", "급성중재"],
    },
    {
        "subject": "정신간호학", "unit": "양극성장애", "difficulty": Difficulty.HARD,
        "question_text": "양극성장애 조증 환자에게 적합한 식이는?",
        "choices": [
            "고열량 유동식",
            "저열량 식이",
            "들고 다니며 먹을 수 있는 finger food",
            "금식",
            "정맥 영양",
        ],
        "correct_answer": 2,
        "explanation": "조증 환자는 한 자리에 앉아 식사하기 어려우므로 휴대 가능한 finger food가 적절.",
        "tags": ["정신", "조증", "영양간호"],
    },
    {
        "subject": "정신간호학", "unit": "약물치료", "difficulty": Difficulty.HARD,
        "question_text": "리튬(lithium) 치료 환자에게 가장 중요한 모니터링 항목은?",
        "choices": ["체온", "혈청 리튬 농도", "혈압", "맥박", "체중"],
        "correct_answer": 1,
        "explanation": "치료 농도 0.6~1.2 mEq/L. 1.5 이상에서 독성 증상(떨림, 설사, 의식변화) 발생.",
        "tags": ["정신", "리튬", "약물모니터링"],
    },
    {
        "subject": "정신간호학", "unit": "약물치료", "difficulty": Difficulty.MEDIUM,
        "question_text": "정형 항정신병약물의 추체외로증상이 아닌 것은?",
        "choices": ["급성 근긴장이상", "정좌불능증", "지연성 운동이상증", "파킨슨증", "구갈"],
        "correct_answer": 4,
        "explanation": "EPS 4종: 급성 근긴장이상, 정좌불능증, 파킨슨증, 지연성 운동이상증. 구갈은 항콜린성 부작용.",
        "tags": ["정신", "항정신병약", "EPS"],
    },
    {
        "subject": "정신간호학", "unit": "치료적관계", "difficulty": Difficulty.MEDIUM,
        "question_text": "치료적 관계의 본질적 요소가 아닌 것은?",
        "choices": ["신뢰", "공감", "진실성", "수용", "개인적 친밀감"],
        "correct_answer": 4,
        "explanation": "치료적 관계는 전문적 경계를 유지하며 사적인 친밀감과 구분되어야 한다.",
        "tags": ["정신", "치료적관계", "의사소통"],
    },
    {
        "subject": "정신간호학", "unit": "위기간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "자살 위험이 매우 높은 환자에게 가장 우선적으로 시행해야 할 것은?",
        "choices": [
            "1:1 관찰",
            "약물 투여",
            "가족 면회 제한",
            "운동 권유",
            "독서 권유",
        ],
        "correct_answer": 0,
        "explanation": "자살 고위험군은 24시간 1:1 관찰과 위험물 제거가 우선.",
        "tags": ["정신", "자살예방", "위기"],
    },
    {
        "subject": "정신간호학", "unit": "물질사용장애", "difficulty": Difficulty.HARD,
        "question_text": "알코올 금단 섬망(DT)의 가장 위험한 합병증은?",
        "choices": ["환시", "발작", "심혈관 허탈/사망", "수면장애", "식욕부진"],
        "correct_answer": 2,
        "explanation": "치료하지 않으면 사망률이 5~15%에 달한다. 벤조디아제핀 투여가 핵심.",
        "tags": ["정신", "알코올", "금단섬망"],
    },
    {
        "subject": "정신간호학", "unit": "방어기제", "difficulty": Difficulty.MEDIUM,
        "question_text": "수용할 수 없는 충동을 사회적으로 인정되는 활동으로 전환하는 방어기제는?",
        "choices": ["억압", "투사", "승화", "반동형성", "합리화"],
        "correct_answer": 2,
        "explanation": "승화(sublimation)는 가장 성숙한 방어기제. 예: 공격성을 운동으로 전환.",
        "tags": ["정신", "방어기제", "심리"],
    },
    # ============ 지역사회간호학 (10) ============
    {
        "subject": "지역사회간호학", "unit": "보건사업", "difficulty": Difficulty.MEDIUM,
        "question_text": "1차 예방에 해당하는 활동은?",
        "choices": [
            "고혈압 환자의 약물복용 교육",
            "암 조기검진",
            "예방접종",
            "재활치료",
            "투석",
        ],
        "correct_answer": 2,
        "explanation": "1차 예방: 건강증진/특이예방(예방접종). 2차: 조기진단/조기치료. 3차: 재활/합병증 예방.",
        "tags": ["지역사회", "예방", "보건교육"],
    },
    {
        "subject": "지역사회간호학", "unit": "역학", "difficulty": Difficulty.MEDIUM,
        "question_text": "발생률(incidence rate) 계산의 분자는?",
        "choices": [
            "특정 시점의 환자수",
            "특정 기간의 신환자수",
            "전체 사망자수",
            "치유된 환자수",
            "전체 인구수",
        ],
        "correct_answer": 1,
        "explanation": "발생률 = 일정 기간 새로 발생한 환자수 / 위험인구. 유병률은 시점 환자수.",
        "tags": ["지역사회", "역학", "발생률"],
    },
    {
        "subject": "지역사회간호학", "unit": "감염병관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "감염병 신고체계에서 즉시 신고해야 하는 1급 감염병에 해당하는 것은?",
        "choices": ["결핵", "에볼라바이러스병", "수두", "B형간염", "독감"],
        "correct_answer": 1,
        "explanation": "1급은 생물테러감염병/치명률 높은 신종으로 즉시 신고. 에볼라, 페스트, 두창 등.",
        "tags": ["지역사회", "감염병", "신고체계"],
    },
    {
        "subject": "지역사회간호학", "unit": "모자보건", "difficulty": Difficulty.EASY,
        "question_text": "영아사망률 계산에서 분자는?",
        "choices": [
            "1세 미만 사망아 수",
            "신생아 사망 수",
            "출생아 수",
            "임신 사망 수",
            "5세 미만 사망 수",
        ],
        "correct_answer": 0,
        "explanation": "영아사망률 = 1세 미만 사망아수 / 1년간 출생아수 × 1000.",
        "tags": ["지역사회", "모자보건", "영아사망률"],
    },
    {
        "subject": "지역사회간호학", "unit": "지역사회사정", "difficulty": Difficulty.MEDIUM,
        "question_text": "지역사회 간호사정 자료수집 방법 중 객관성이 가장 높은 것은?",
        "choices": ["관찰", "면담", "설문", "공식 통계자료", "개인 의견"],
        "correct_answer": 3,
        "explanation": "공식 통계는 검증된 데이터로 객관성이 가장 높다.",
        "tags": ["지역사회", "사정", "자료수집"],
    },
    {
        "subject": "지역사회간호학", "unit": "건강증진", "difficulty": Difficulty.MEDIUM,
        "question_text": "오타와 헌장의 5대 활동영역이 아닌 것은?",
        "choices": [
            "건강한 공공정책 수립",
            "지지적 환경 조성",
            "지역사회 활동 강화",
            "개인 기술 개발",
            "약물치료 강화",
        ],
        "correct_answer": 4,
        "explanation": "오타와 5대 영역: 정책수립, 환경조성, 지역사회활동, 개인기술, 보건의료방향 재설정.",
        "tags": ["지역사회", "건강증진", "오타와헌장"],
    },
    {
        "subject": "지역사회간호학", "unit": "방문간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "방문간호 시 가장 우선적으로 해야 할 일은?",
        "choices": ["병력 청취", "신체 검진", "안전 사정", "교육 자료 배포", "투약"],
        "correct_answer": 2,
        "explanation": "가정환경의 안전(낙상위험, 위생, 화재 등)을 우선 사정한다.",
        "tags": ["지역사회", "방문간호"],
    },
    {
        "subject": "지역사회간호학", "unit": "산업간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "산업재해의 주요 원인 중 인적요인에 해당하는 것은?",
        "choices": [
            "안전장비 미흡",
            "불완전한 작업환경",
            "작업자의 부주의",
            "기계 결함",
            "조명 부족",
        ],
        "correct_answer": 2,
        "explanation": "인적요인: 부주의, 피로, 기술부족. 물적요인: 환경/기계.",
        "tags": ["지역사회", "산업간호", "재해"],
    },
    {
        "subject": "지역사회간호학", "unit": "학교보건", "difficulty": Difficulty.EASY,
        "question_text": "학교 응급실 비치품으로 적절하지 않은 것은?",
        "choices": ["반창고", "소독제", "체온계", "처방전 없는 항생제", "냉찜질팩"],
        "correct_answer": 3,
        "explanation": "처방 약물(특히 항생제)은 학교 비치품에서 제외.",
        "tags": ["지역사회", "학교보건"],
    },
    {
        "subject": "지역사회간호학", "unit": "가족간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "가족 사정의 도구로 가족 구조와 관계를 도식화하는 것은?",
        "choices": ["사회지지도", "가계도(genogram)", "가족 연표", "외부체계도", "가족생활주기"],
        "correct_answer": 1,
        "explanation": "Genogram은 3세대 이상의 가족 구조와 관계, 질병력을 시각화한다.",
        "tags": ["지역사회", "가족간호", "가계도"],
    },
    # ============ 기본간호학 (6) ============
    {
        "subject": "기본간호학", "unit": "활력징후", "difficulty": Difficulty.EASY,
        "question_text": "성인의 정상 맥박 범위는?",
        "choices": ["40~60회/분", "60~100회/분", "100~120회/분", "120~140회/분", "140~160회/분"],
        "correct_answer": 1,
        "explanation": "정상 성인 맥박 60~100회/분. 60 미만 서맥, 100 초과 빈맥.",
        "tags": ["기본간호", "활력징후"],
    },
    {
        "subject": "기본간호학", "unit": "감염관리", "difficulty": Difficulty.MEDIUM,
        "question_text": "표준주의(Standard Precautions)의 핵심 원칙은?",
        "choices": [
            "감염병 환자만 적용",
            "모든 환자의 혈액·체액을 잠재적 감염원으로 간주",
            "고위험군만 적용",
            "혈액 노출 시에만 적용",
            "수술 환자만 적용",
        ],
        "correct_answer": 1,
        "explanation": "표준주의는 모든 환자에게 적용되며, 감염 여부와 무관하게 모든 체액을 감염성으로 본다.",
        "tags": ["기본간호", "감염관리", "표준주의"],
    },
    {
        "subject": "기본간호학", "unit": "투약", "difficulty": Difficulty.MEDIUM,
        "question_text": "투약의 5R(5 Rights)이 아닌 것은?",
        "choices": ["정확한 환자", "정확한 약물", "정확한 용량", "정확한 가격", "정확한 시간"],
        "correct_answer": 3,
        "explanation": "5R: Right patient, drug, dose, route, time.",
        "tags": ["기본간호", "투약", "5R"],
    },
    {
        "subject": "기본간호학", "unit": "체위", "difficulty": Difficulty.EASY,
        "question_text": "쇼크 환자의 적절한 체위는?",
        "choices": [
            "좌위",
            "반좌위",
            "변형 트렌델렌버그(modified Trendelenburg)",
            "엎드린 자세",
            "쇄석위",
        ],
        "correct_answer": 2,
        "explanation": "다리만 거상하는 변형 트렌델렌버그가 정맥 환류를 도와 뇌 관류 유지에 도움.",
        "tags": ["기본간호", "체위", "쇼크"],
    },
    {
        "subject": "기본간호학", "unit": "상처간호", "difficulty": Difficulty.MEDIUM,
        "question_text": "욕창 1단계의 특징은?",
        "choices": [
            "표재성 피부 손실",
            "압력을 제거해도 사라지지 않는 발적",
            "전층 피부 손실",
            "근육 노출",
            "뼈 노출",
        ],
        "correct_answer": 1,
        "explanation": "1단계: non-blanching erythema(눌러도 창백해지지 않는 발적).",
        "tags": ["기본간호", "욕창", "피부간호"],
    },
    {
        "subject": "기본간호학", "unit": "영양", "difficulty": Difficulty.MEDIUM,
        "question_text": "비위관 영양 전 가장 먼저 확인해야 할 사항은?",
        "choices": [
            "영양액 온도",
            "비위관 위치 확인",
            "환자 체위",
            "활력징후",
            "투약 시간",
        ],
        "correct_answer": 1,
        "explanation": "비위관이 위 내에 있는지 위 내용물 흡인/pH 검사로 확인 후 주입한다.",
        "tags": ["기본간호", "비위관", "영양간호"],
    },
    # ============ 보건의약관계법규 (5) ============
    {
        "subject": "보건의약관계법규", "unit": "의료법", "difficulty": Difficulty.MEDIUM,
        "question_text": "의료법상 간호사의 면허 결격사유에 해당하지 않는 것은?",
        "choices": [
            "정신질환자",
            "마약중독자",
            "금치산자",
            "면허 취소 후 1년 미경과자",
            "고등학교 졸업자",
        ],
        "correct_answer": 4,
        "explanation": "고졸은 결격사유가 아님. 결격: 정신질환, 마약중독, 금치산, 면허취소 후 일정기간 미경과.",
        "tags": ["법규", "의료법", "면허"],
    },
    {
        "subject": "보건의약관계법규", "unit": "감염병예방법", "difficulty": Difficulty.MEDIUM,
        "question_text": "감염병 예방법상 1급 감염병의 신고 시점은?",
        "choices": ["즉시", "24시간 이내", "7일 이내", "30일 이내", "다음 분기"],
        "correct_answer": 0,
        "explanation": "1급은 즉시(전화/팩스), 2~3급은 24시간 이내 신고.",
        "tags": ["법규", "감염병", "신고"],
    },
    {
        "subject": "보건의약관계법규", "unit": "응급의료법", "difficulty": Difficulty.MEDIUM,
        "question_text": "응급의료에 관한 법률에서 응급환자에 대한 응급의료 거부 시 처벌되는 것은?",
        "choices": [
            "정당한 사유 없는 거부",
            "환자가 비응급일 때",
            "전원이 필요할 때",
            "의료진 부족 시",
            "보호자 동의 없을 때",
        ],
        "correct_answer": 0,
        "explanation": "정당한 사유 없이 응급의료를 거부/기피한 의료인은 처벌 대상.",
        "tags": ["법규", "응급의료법"],
    },
    {
        "subject": "보건의약관계법규", "unit": "국민건강보험법", "difficulty": Difficulty.EASY,
        "question_text": "우리나라 국민건강보험의 가입 형태는?",
        "choices": ["임의가입", "선택가입", "강제가입", "단체가입만", "직장가입만"],
        "correct_answer": 2,
        "explanation": "전 국민 강제가입(직장가입자 + 지역가입자).",
        "tags": ["법규", "건강보험"],
    },
    {
        "subject": "보건의약관계법규", "unit": "의료법", "difficulty": Difficulty.HARD,
        "question_text": "의료법상 의료인의 비밀누설 금지 대상이 아닌 것은?",
        "choices": [
            "환자의 진료기록",
            "환자의 가족력",
            "환자의 소속회사",
            "법령에 따른 정보 제공",
            "환자의 진단명",
        ],
        "correct_answer": 3,
        "explanation": "법령에 따른 의무 신고(감염병 등)는 비밀누설 금지의 예외.",
        "tags": ["법규", "의료법", "비밀유지"],
    },
]
