"""물리치료학과 시드 문제 (60문항).

신경계 15 / 근골격계 15 / 심폐 8 / 소아 7 / 진단평가 8 / 의료법규 7
"""

from app.models.enums import Department, Difficulty, QuestionType

DEPT = Department.PHYSICAL_THERAPY
TYPE = QuestionType.SINGLE_CHOICE
SOURCE = "샘플 시드 (Day 3)"

PT_QUESTIONS = [
    # ============ 신경계물리치료 (15) ============
    {
        "subject": "신경계물리치료", "unit": "뇌졸중", "difficulty": Difficulty.MEDIUM,
        "question_text": "뇌졸중 환자의 편마비 회복을 위한 Brunnstrom 단계 중 협응 운동이 가능한 단계는?",
        "choices": ["1단계", "2단계", "3단계", "5단계", "6단계"],
        "correct_answer": 4,
        "explanation": "Brunnstrom 6단계: 정상에 가까운 협응 운동 가능. 3단계는 수의적 공동운동.",
        "tags": ["신경", "뇌졸중", "Brunnstrom"],
    },
    {
        "subject": "신경계물리치료", "unit": "뇌졸중", "difficulty": Difficulty.MEDIUM,
        "question_text": "좌측 뇌손상 환자에게서 흔히 나타나는 증상은?",
        "choices": ["좌측 편마비", "우측 편마비와 실어증", "양측 마비", "안면 마비만", "감각 소실만"],
        "correct_answer": 1,
        "explanation": "좌측 뇌(보통 우세 반구) 손상은 우측 편마비와 언어장애(실어증)를 동반한다.",
        "tags": ["신경", "뇌졸중", "편마비"],
    },
    {
        "subject": "신경계물리치료", "unit": "척수손상", "difficulty": Difficulty.HARD,
        "question_text": "C6 완전 척수손상 환자가 독립적으로 수행할 수 있는 활동은?",
        "choices": [
            "보행",
            "휠체어 이동 및 자가 도뇨",
            "계단 오르기",
            "달리기",
            "점프",
        ],
        "correct_answer": 1,
        "explanation": "C6 손상자는 손목 신전근 사용 가능 → 휠체어 추진과 자가 도뇨 가능.",
        "tags": ["신경", "척수손상", "ADL"],
    },
    {
        "subject": "신경계물리치료", "unit": "척수손상", "difficulty": Difficulty.MEDIUM,
        "question_text": "척수손상 환자의 자율신경 반사부전(autonomic dysreflexia)의 가장 흔한 원인은?",
        "choices": ["저혈압", "방광 팽만", "고열", "기립성 저혈압", "근경직"],
        "correct_answer": 1,
        "explanation": "T6 이상 손상자에서 방광/직장 팽만 등 손상부 이하 자극으로 발생. 즉시 자극원 제거.",
        "tags": ["신경", "척수손상", "응급"],
    },
    {
        "subject": "신경계물리치료", "unit": "파킨슨", "difficulty": Difficulty.MEDIUM,
        "question_text": "파킨슨병의 4대 증상이 아닌 것은?",
        "choices": ["진전", "근경직", "운동완만", "자세 불안정", "마비"],
        "correct_answer": 4,
        "explanation": "파킨슨병 4대 증상: 떨림, 강직, 운동완서, 자세불안정. 마비는 해당 안 됨.",
        "tags": ["신경", "파킨슨"],
    },
    {
        "subject": "신경계물리치료", "unit": "파킨슨", "difficulty": Difficulty.MEDIUM,
        "question_text": "파킨슨병 환자의 보행 훈련 시 가장 효과적인 단서(cue)는?",
        "choices": ["청각 단서(메트로놈)", "시각 단서만", "촉각 단서만", "후각 단서", "단서 없음"],
        "correct_answer": 0,
        "explanation": "리듬 청각 자극(RAS)이 파킨슨 보행의 동결과 보폭 단축을 개선한다.",
        "tags": ["신경", "파킨슨", "보행"],
    },
    {
        "subject": "신경계물리치료", "unit": "다발경화증", "difficulty": Difficulty.MEDIUM,
        "question_text": "다발경화증 환자의 운동 시 주의해야 할 점은?",
        "choices": [
            "고온 환경에서 운동",
            "장시간 강도 높은 운동",
            "체온 상승 회피와 적절한 휴식",
            "수영장 사용 금지",
            "운동 금기",
        ],
        "correct_answer": 2,
        "explanation": "Uhthoff 현상: 체온 상승 시 신경증상 악화. 시원한 환경에서 짧은 운동을 자주 한다.",
        "tags": ["신경", "다발경화증", "Uhthoff"],
    },
    {
        "subject": "신경계물리치료", "unit": "신경발달", "difficulty": Difficulty.HARD,
        "question_text": "Bobath 접근법(NDT)의 주요 목표는?",
        "choices": [
            "근력 강화",
            "비정상 운동 패턴 억제와 정상 자세 반응 촉진",
            "관절가동범위 증가",
            "지구력 향상",
            "통증 감소",
        ],
        "correct_answer": 1,
        "explanation": "Bobath/NDT는 비정상 톤과 패턴을 억제하고 정상 운동을 촉진한다.",
        "tags": ["신경", "Bobath", "NDT"],
    },
    {
        "subject": "신경계물리치료", "unit": "균형", "difficulty": Difficulty.MEDIUM,
        "question_text": "Berg Balance Scale의 총점은?",
        "choices": ["20점", "36점", "56점", "100점", "120점"],
        "correct_answer": 2,
        "explanation": "BBS는 14개 항목 × 0~4점 = 총 56점.",
        "tags": ["신경", "균형", "평가도구"],
    },
    {
        "subject": "신경계물리치료", "unit": "보행분석", "difficulty": Difficulty.MEDIUM,
        "question_text": "정상 보행 주기에서 입각기(stance phase)가 차지하는 비율은?",
        "choices": ["20%", "40%", "50%", "60%", "80%"],
        "correct_answer": 3,
        "explanation": "정상 보행: 입각기 60%, 유각기 40%.",
        "tags": ["신경", "보행", "보행주기"],
    },
    {
        "subject": "신경계물리치료", "unit": "말초신경", "difficulty": Difficulty.MEDIUM,
        "question_text": "수근관 증후군(carpal tunnel syndrome)에서 압박되는 신경은?",
        "choices": ["요골신경", "정중신경", "척골신경", "근피신경", "액와신경"],
        "correct_answer": 1,
        "explanation": "수근관에서 정중신경이 압박. 무지구 위축, 야간 통증, Tinel sign 양성.",
        "tags": ["신경", "말초신경", "CTS"],
    },
    {
        "subject": "신경계물리치료", "unit": "말초신경", "difficulty": Difficulty.MEDIUM,
        "question_text": "Erb's palsy에서 손상되는 신경근은?",
        "choices": ["C3-C4", "C5-C6", "C7-C8", "T1-T2", "L4-L5"],
        "correct_answer": 1,
        "explanation": "Erb-Duchenne 마비는 상부 완신경총(C5-C6) 손상. 'waiter's tip' 자세.",
        "tags": ["신경", "완신경총", "Erb"],
    },
    {
        "subject": "신경계물리치료", "unit": "치매", "difficulty": Difficulty.MEDIUM,
        "question_text": "치매 환자의 운동치료 원칙으로 옳지 않은 것은?",
        "choices": [
            "단순하고 반복적인 동작",
            "친숙한 환경",
            "복잡한 다단계 지시",
            "긍정적 강화",
            "짧은 회기",
        ],
        "correct_answer": 2,
        "explanation": "복잡한 지시는 인지 부하를 증가시켜 부적절. 단순/반복/친숙이 핵심.",
        "tags": ["신경", "치매", "노인"],
    },
    {
        "subject": "신경계물리치료", "unit": "전기치료", "difficulty": Difficulty.MEDIUM,
        "question_text": "기능적 전기자극(FES)의 주된 적용 대상은?",
        "choices": [
            "정상 근육",
            "상위운동신경원 손상으로 마비된 근육",
            "골절 부위",
            "급성 염증",
            "악성종양",
        ],
        "correct_answer": 1,
        "explanation": "UMN 손상으로 운동 명령은 안 가지만 말초신경/근육은 살아있는 경우 FES로 수축 유도.",
        "tags": ["신경", "FES", "전기치료"],
    },
    {
        "subject": "신경계물리치료", "unit": "재활", "difficulty": Difficulty.HARD,
        "question_text": "뇌졸중 환자의 견갑통(shoulder pain) 예방을 위한 가장 중요한 중재는?",
        "choices": [
            "수동 어깨 운동 금지",
            "올바른 자세 지지와 support sling 사용",
            "강한 견인",
            "냉찜질만",
            "약물치료만",
        ],
        "correct_answer": 1,
        "explanation": "이완성 마비기에는 견관절 아탈구 예방이 중요. 적절한 지지와 자세 관리가 핵심.",
        "tags": ["신경", "뇌졸중", "견갑통"],
    },
    # ============ 근골격계물리치료 (15) ============
    {
        "subject": "근골격계물리치료", "unit": "어깨", "difficulty": Difficulty.MEDIUM,
        "question_text": "회전근개 손상 중 가장 흔히 손상되는 근육은?",
        "choices": ["견갑하근", "극상근(supraspinatus)", "극하근", "소원근", "삼각근"],
        "correct_answer": 1,
        "explanation": "견봉 아래 좁은 공간을 지나는 극상근이 충돌증후군과 함께 가장 흔히 손상된다.",
        "tags": ["근골격", "회전근개", "어깨"],
    },
    {
        "subject": "근골격계물리치료", "unit": "어깨", "difficulty": Difficulty.MEDIUM,
        "question_text": "동결견(frozen shoulder)의 가장 큰 특징은?",
        "choices": [
            "통증만",
            "능동·수동 모두 ROM 제한",
            "능동만 제한",
            "수동만 제한",
            "근력 약화만",
        ],
        "correct_answer": 1,
        "explanation": "관절낭 유착으로 능동·수동 모두 외회전 위주로 제한.",
        "tags": ["근골격", "동결견", "어깨"],
    },
    {
        "subject": "근골격계물리치료", "unit": "무릎", "difficulty": Difficulty.MEDIUM,
        "question_text": "전방십자인대(ACL) 검사로 가장 적절한 것은?",
        "choices": ["McMurray test", "Lachman test", "Apley test", "Thomas test", "Phalen test"],
        "correct_answer": 1,
        "explanation": "Lachman test가 ACL 파열 진단에 가장 민감(굴곡 20~30도).",
        "tags": ["근골격", "무릎", "ACL"],
    },
    {
        "subject": "근골격계물리치료", "unit": "무릎", "difficulty": Difficulty.HARD,
        "question_text": "무릎 전치환술 후 재활 초기 단계의 우선 목표는?",
        "choices": [
            "근력 강화",
            "통증·부종 관리와 ROM 회복",
            "달리기",
            "점프 훈련",
            "스포츠 복귀",
        ],
        "correct_answer": 1,
        "explanation": "초기 1~2주는 부종/통증 관리, 90도 굴곡 확보가 핵심.",
        "tags": ["근골격", "TKR", "재활"],
    },
    {
        "subject": "근골격계물리치료", "unit": "허리", "difficulty": Difficulty.MEDIUM,
        "question_text": "요추 추간판 탈출증의 신경학적 검사로 적절한 것은?",
        "choices": [
            "Phalen test",
            "Straight Leg Raising(SLR)",
            "Apley test",
            "McMurray test",
            "Thomas test",
        ],
        "correct_answer": 1,
        "explanation": "SLR(하지직거상) 검사가 양성이면 좌골신경근 압박을 의심.",
        "tags": ["근골격", "허리", "추간판"],
    },
    {
        "subject": "근골격계물리치료", "unit": "허리", "difficulty": Difficulty.MEDIUM,
        "question_text": "맥켄지(McKenzie) 신전 운동이 적용되는 환자는?",
        "choices": [
            "굴곡으로 통증 완화되는 환자",
            "신전으로 통증 완화되는 환자",
            "회전 시 악화 환자",
            "골절 환자",
            "급성 골절",
        ],
        "correct_answer": 1,
        "explanation": "디스크 후방 탈출 환자에서 신전으로 centralization되면 McKenzie 신전 운동 적용.",
        "tags": ["근골격", "허리", "McKenzie"],
    },
    {
        "subject": "근골격계물리치료", "unit": "발/발목", "difficulty": Difficulty.MEDIUM,
        "question_text": "발목 염좌 중 가장 흔한 손상 기전은?",
        "choices": ["내번 손상", "외번 손상", "회내 손상", "회외 손상", "굴곡 손상"],
        "correct_answer": 0,
        "explanation": "내번(inversion) 손상으로 ATFL이 가장 흔히 손상.",
        "tags": ["근골격", "발목", "염좌"],
    },
    {
        "subject": "근골격계물리치료", "unit": "골절", "difficulty": Difficulty.MEDIUM,
        "question_text": "골절 치유 단계 중 임시 가골이 형성되는 시기는?",
        "choices": ["혈종 형성기", "염증기", "골 가골 형성기", "성숙기", "재형성기"],
        "correct_answer": 2,
        "explanation": "골절 후 약 2~3주에 가골(callus)이 형성된다.",
        "tags": ["근골격", "골절", "치유단계"],
    },
    {
        "subject": "근골격계물리치료", "unit": "척추", "difficulty": Difficulty.MEDIUM,
        "question_text": "정상 성인의 경추 만곡은?",
        "choices": ["후만", "전만", "측만", "직선", "변형"],
        "correct_answer": 1,
        "explanation": "경추는 전만(lordosis), 흉추는 후만, 요추는 전만, 천추는 후만.",
        "tags": ["근골격", "척추", "만곡"],
    },
    {
        "subject": "근골격계물리치료", "unit": "척추", "difficulty": Difficulty.HARD,
        "question_text": "특발성 척추측만증의 진단 기준 Cobb angle은?",
        "choices": ["5도 이상", "10도 이상", "20도 이상", "30도 이상", "45도 이상"],
        "correct_answer": 1,
        "explanation": "Cobb angle 10도 이상이면 측만증으로 진단. 20도부터 보조기, 40~50도부터 수술 고려.",
        "tags": ["근골격", "척추측만", "Cobb"],
    },
    {
        "subject": "근골격계물리치료", "unit": "관절염", "difficulty": Difficulty.MEDIUM,
        "question_text": "류마티스 관절염과 골관절염의 차이로 옳은 것은?",
        "choices": [
            "RA는 기상 시 강직이 30분 이상 지속",
            "OA는 양측 대칭",
            "RA는 큰 관절만 침범",
            "OA는 자가면역 질환",
            "RA는 노인에서만 발생",
        ],
        "correct_answer": 0,
        "explanation": "RA는 morning stiffness가 1시간 이상 지속, 양측 대칭, 작은 관절(MCP/PIP) 침범.",
        "tags": ["근골격", "관절염", "감별진단"],
    },
    {
        "subject": "근골격계물리치료", "unit": "근막통증", "difficulty": Difficulty.MEDIUM,
        "question_text": "근막통증증후군의 특징은?",
        "choices": [
            "전신 통증",
            "특정 근육에 압통점(trigger point)과 연관통",
            "관절통",
            "신경통",
            "혈관통",
        ],
        "correct_answer": 1,
        "explanation": "Trigger point가 핵심. 압박 시 referred pain 발생.",
        "tags": ["근골격", "근막통증", "TrP"],
    },
    {
        "subject": "근골격계물리치료", "unit": "도수치료", "difficulty": Difficulty.HARD,
        "question_text": "Maitland 등급 중 통증 완화를 위해 사용하는 등급은?",
        "choices": ["I~II", "III", "IV", "V", "모든 등급"],
        "correct_answer": 0,
        "explanation": "I~II 등급은 통증 완화 목적, III~IV는 가동범위 증가, V는 thrust(고속저진폭).",
        "tags": ["근골격", "Maitland", "도수치료"],
    },
    {
        "subject": "근골격계물리치료", "unit": "운동치료", "difficulty": Difficulty.MEDIUM,
        "question_text": "PNF의 D1 굴곡 패턴의 어깨 동작은?",
        "choices": [
            "굴곡-내전-외회전",
            "굴곡-외전-내회전",
            "신전-외전-내회전",
            "신전-내전-외회전",
            "굴곡-내전-내회전",
        ],
        "correct_answer": 0,
        "explanation": "PNF D1 flexion: 견관절 굴곡-내전-외회전.",
        "tags": ["근골격", "PNF", "운동치료"],
    },
    {
        "subject": "근골격계물리치료", "unit": "물리적인자", "difficulty": Difficulty.MEDIUM,
        "question_text": "초음파 치료의 깊이가 가장 깊은 주파수는?",
        "choices": ["1 MHz", "3 MHz", "5 MHz", "10 MHz", "동일"],
        "correct_answer": 0,
        "explanation": "1 MHz는 5cm까지, 3 MHz는 1~2cm까지 침투.",
        "tags": ["근골격", "초음파", "물리적인자"],
    },
    # ============ 심폐물리치료 (8) ============
    {
        "subject": "심폐물리치료", "unit": "호흡", "difficulty": Difficulty.MEDIUM,
        "question_text": "COPD 환자에게 권장되는 호흡법은?",
        "choices": [
            "흉식 호흡",
            "입술오므리기 호흡(pursed-lip)",
            "빠른 호흡",
            "얕은 호흡",
            "참기",
        ],
        "correct_answer": 1,
        "explanation": "Pursed-lip breathing은 PEEP를 유지해 기도 허탈을 방지하고 호기를 효과적으로.",
        "tags": ["심폐", "COPD", "호흡법"],
    },
    {
        "subject": "심폐물리치료", "unit": "기관지위생", "difficulty": Difficulty.MEDIUM,
        "question_text": "체위배액의 효과를 가장 잘 얻을 수 있는 자세는?",
        "choices": [
            "앉은 자세",
            "선 자세",
            "분비물이 있는 폐 부위가 위로 가도록 자세",
            "엎드린 자세",
            "측위만",
        ],
        "correct_answer": 2,
        "explanation": "중력을 이용하여 분비물이 큰 기도로 흘러내리도록 환부를 위쪽에 둔다.",
        "tags": ["심폐", "체위배액", "기관지위생"],
    },
    {
        "subject": "심폐물리치료", "unit": "심장재활", "difficulty": Difficulty.HARD,
        "question_text": "심장재활 프로그램에서 운동 강도 결정에 사용되는 가장 적절한 지표는?",
        "choices": [
            "연령",
            "체중",
            "Borg 자각운동강도(RPE)와 심박수",
            "혈압만",
            "성별",
        ],
        "correct_answer": 2,
        "explanation": "RPE 11~14, 안정시 심박수 + 20~30 bpm 범위가 일반적 권장.",
        "tags": ["심폐", "심장재활", "운동강도"],
    },
    {
        "subject": "심폐물리치료", "unit": "운동검사", "difficulty": Difficulty.MEDIUM,
        "question_text": "6분 보행검사(6MWT)의 주요 평가 항목은?",
        "choices": [
            "최대 심박수",
            "걸은 거리와 호흡곤란 정도",
            "혈압만",
            "산소포화도만",
            "근력",
        ],
        "correct_answer": 1,
        "explanation": "6분간 걸은 거리(m)와 운동 전후 SpO2/RPE/HR 변화를 측정.",
        "tags": ["심폐", "6MWT", "운동검사"],
    },
    {
        "subject": "심폐물리치료", "unit": "흉부타진", "difficulty": Difficulty.MEDIUM,
        "question_text": "흉부타진(percussion)의 금기증이 아닌 것은?",
        "choices": ["갈비뼈 골절", "객혈", "기흉", "안정형 만성기관지염", "골다공증"],
        "correct_answer": 3,
        "explanation": "안정형 만성기관지염은 적응증. 골절/객혈/기흉/골다공증은 금기.",
        "tags": ["심폐", "흉부타진", "금기"],
    },
    {
        "subject": "심폐물리치료", "unit": "산소요법", "difficulty": Difficulty.MEDIUM,
        "question_text": "운동 중 산소포화도(SpO2)가 어느 정도 떨어지면 운동을 중단해야 하는가?",
        "choices": ["95% 미만", "92% 미만", "88% 미만", "85% 미만", "80% 미만"],
        "correct_answer": 2,
        "explanation": "일반적으로 88% 미만이면 운동 중단. 환자에 따라 90% 기준 적용.",
        "tags": ["심폐", "산소포화도", "운동"],
    },
    {
        "subject": "심폐물리치료", "unit": "흉부확장운동", "difficulty": Difficulty.EASY,
        "question_text": "수술 후 폐합병증 예방을 위한 가장 일반적인 운동은?",
        "choices": ["스쿼트", "심호흡과 기침", "복근운동", "하지 근력", "요가"],
        "correct_answer": 1,
        "explanation": "심호흡과 효과적인 기침으로 폐 확장과 분비물 제거를 돕는다.",
        "tags": ["심폐", "수술후", "예방"],
    },
    {
        "subject": "심폐물리치료", "unit": "심전도", "difficulty": Difficulty.HARD,
        "question_text": "심전도에서 P파가 나타내는 것은?",
        "choices": ["심방 탈분극", "심실 탈분극", "심실 재분극", "방실결절 전도", "심방 재분극"],
        "correct_answer": 0,
        "explanation": "P파 = 심방 탈분극. QRS = 심실 탈분극. T파 = 심실 재분극.",
        "tags": ["심폐", "심전도", "ECG"],
    },
    # ============ 소아물리치료 (7) ============
    {
        "subject": "소아물리치료", "unit": "발달", "difficulty": Difficulty.MEDIUM,
        "question_text": "정상 영아가 혼자 앉는 시기는?",
        "choices": ["3개월", "4개월", "6개월", "9개월", "12개월"],
        "correct_answer": 2,
        "explanation": "6개월경에 지지 없이 앉기 가능.",
        "tags": ["소아", "발달이정표"],
    },
    {
        "subject": "소아물리치료", "unit": "뇌성마비", "difficulty": Difficulty.HARD,
        "question_text": "GMFCS(대운동기능분류) 단계 중 보조기 없이 보행 가능하지만 야외/계단에서 제한이 있는 단계는?",
        "choices": ["Level I", "Level II", "Level III", "Level IV", "Level V"],
        "correct_answer": 1,
        "explanation": "Level II는 실내 보행 가능, 야외/계단 등에서 제한.",
        "tags": ["소아", "뇌성마비", "GMFCS"],
    },
    {
        "subject": "소아물리치료", "unit": "뇌성마비", "difficulty": Difficulty.MEDIUM,
        "question_text": "경직형 뇌성마비 환아의 가장 흔한 자세 이상은?",
        "choices": [
            "외전된 다리",
            "가위자세(scissoring)",
            "굴곡된 척추",
            "신전된 손가락",
            "회전된 머리",
        ],
        "correct_answer": 1,
        "explanation": "내전근의 경직으로 양 다리가 교차되는 가위자세가 특징.",
        "tags": ["소아", "뇌성마비", "경직"],
    },
    {
        "subject": "소아물리치료", "unit": "사경", "difficulty": Difficulty.MEDIUM,
        "question_text": "선천성 근성 사경(torticollis)의 원인 근육은?",
        "choices": [
            "흉쇄유돌근(SCM)",
            "승모근",
            "광경근",
            "이복근",
            "사각근",
        ],
        "correct_answer": 0,
        "explanation": "흉쇄유돌근의 단축으로 머리가 같은 쪽으로 기울고 반대쪽으로 회전.",
        "tags": ["소아", "사경", "SCM"],
    },
    {
        "subject": "소아물리치료", "unit": "이분척추", "difficulty": Difficulty.MEDIUM,
        "question_text": "이분척추(spina bifida) 환아 간호 시 주의사항은?",
        "choices": [
            "라텍스 알레르기 주의",
            "단백질 제한",
            "수분 제한",
            "운동 금지",
            "햇빛 차단",
        ],
        "correct_answer": 0,
        "explanation": "잦은 수술로 라텍스 노출이 많아 알레르기 발생률이 높다.",
        "tags": ["소아", "이분척추"],
    },
    {
        "subject": "소아물리치료", "unit": "근이영양증", "difficulty": Difficulty.HARD,
        "question_text": "Duchenne 근이영양증 환아의 특징적 동작은?",
        "choices": [
            "발끝걷기",
            "Gowers' sign(바닥에서 일어날 때 다리를 짚고 올라옴)",
            "발가락 굴곡",
            "발목 외반",
            "발꿈치 걷기",
        ],
        "correct_answer": 1,
        "explanation": "근위부 근력 약화로 바닥에서 일어설 때 손으로 다리를 짚고 올라오는 Gowers' sign이 특징.",
        "tags": ["소아", "DMD", "Gowers"],
    },
    {
        "subject": "소아물리치료", "unit": "조산아", "difficulty": Difficulty.MEDIUM,
        "question_text": "조산아의 발달 평가 시 보정 연령(corrected age)은 보통 몇 세까지 사용하는가?",
        "choices": ["6개월", "12개월", "18~24개월", "5세", "10세"],
        "correct_answer": 2,
        "explanation": "보통 24개월(2세)까지 보정 연령을 사용한다.",
        "tags": ["소아", "조산아", "보정연령"],
    },
    # ============ 진단평가 (8) ============
    {
        "subject": "물리치료진단평가", "unit": "MMT", "difficulty": Difficulty.EASY,
        "question_text": "MMT(도수근력검사) 4등급의 의미는?",
        "choices": [
            "근수축 없음",
            "근수축만 가능",
            "중력 제거 시 ROM 가능",
            "중력 이긴 ROM + 약간 저항",
            "정상 저항",
        ],
        "correct_answer": 3,
        "explanation": "MMT 4(Good)는 중력에 저항하면서 약간의 저항도 이길 수 있는 상태.",
        "tags": ["평가", "MMT", "근력"],
    },
    {
        "subject": "물리치료진단평가", "unit": "ROM", "difficulty": Difficulty.MEDIUM,
        "question_text": "정상 어깨 굴곡 ROM은?",
        "choices": ["90도", "120도", "150도", "180도", "200도"],
        "correct_answer": 3,
        "explanation": "정상 어깨 굴곡은 0~180도.",
        "tags": ["평가", "ROM", "어깨"],
    },
    {
        "subject": "물리치료진단평가", "unit": "감각", "difficulty": Difficulty.MEDIUM,
        "question_text": "C7 피부분절(dermatome)에 해당하는 부위는?",
        "choices": ["엄지", "검지", "중지", "약지", "소지"],
        "correct_answer": 2,
        "explanation": "C7은 중지(middle finger)에 해당.",
        "tags": ["평가", "Dermatome", "신경"],
    },
    {
        "subject": "물리치료진단평가", "unit": "심부건반사", "difficulty": Difficulty.MEDIUM,
        "question_text": "슬개건반사(patellar reflex)는 어느 신경근 수준을 평가하는가?",
        "choices": ["L2-L3", "L3-L4", "L4-L5", "L5-S1", "S1-S2"],
        "correct_answer": 1,
        "explanation": "슬개건반사는 L3-L4(주로 L4) 평가. 아킬레스건반사는 S1-S2.",
        "tags": ["평가", "DTR", "L4"],
    },
    {
        "subject": "물리치료진단평가", "unit": "ADL", "difficulty": Difficulty.MEDIUM,
        "question_text": "ADL 평가 도구로 가장 널리 사용되는 것은?",
        "choices": ["Berg Scale", "FIM(Functional Independence Measure)", "Tinetti", "MMSE", "Borg"],
        "correct_answer": 1,
        "explanation": "FIM은 18개 항목 × 1~7점 = 총 126점, 일상생활 독립성을 평가.",
        "tags": ["평가", "ADL", "FIM"],
    },
    {
        "subject": "물리치료진단평가", "unit": "통증평가", "difficulty": Difficulty.EASY,
        "question_text": "통증 평가 도구 중 0~10점으로 표시하는 것은?",
        "choices": [
            "VAS(Visual Analog Scale)",
            "NRS(Numeric Rating Scale)",
            "McGill Pain Questionnaire",
            "FACES Scale",
            "FLACC",
        ],
        "correct_answer": 1,
        "explanation": "NRS는 0(통증 없음)~10(최악) 숫자 평가. VAS는 10cm 선상에 표시.",
        "tags": ["평가", "통증", "NRS"],
    },
    {
        "subject": "물리치료진단평가", "unit": "균형평가", "difficulty": Difficulty.MEDIUM,
        "question_text": "낙상 위험을 평가하는 검사가 아닌 것은?",
        "choices": ["TUG(Timed Up and Go)", "Berg Balance Scale", "Tinetti", "MMT", "Functional Reach"],
        "correct_answer": 3,
        "explanation": "MMT는 근력 평가. 나머지는 균형/낙상 평가.",
        "tags": ["평가", "균형", "낙상"],
    },
    {
        "subject": "물리치료진단평가", "unit": "관찰", "difficulty": Difficulty.MEDIUM,
        "question_text": "관절가동범위(ROM) 측정에 사용하는 도구는?",
        "choices": ["측각기(goniometer)", "근력계", "심박계", "혈압계", "초음파"],
        "correct_answer": 0,
        "explanation": "Goniometer가 표준 ROM 측정 도구.",
        "tags": ["평가", "ROM", "도구"],
    },
    # ============ 의료법규 (7) ============
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.MEDIUM,
        "question_text": "물리치료사 면허 발급 기관은?",
        "choices": ["대한물리치료사협회", "보건복지부장관", "교육부장관", "병원장", "지자체"],
        "correct_answer": 1,
        "explanation": "의료기사 면허는 보건복지부장관이 발급.",
        "tags": ["법규", "면허"],
    },
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.MEDIUM,
        "question_text": "의료기사의 업무 범위로 옳은 것은?",
        "choices": [
            "독립적 진단",
            "의사의 지도 아래 업무 수행",
            "약물 처방",
            "수술 보조 단독",
            "간호사 지도 아래 업무",
        ],
        "correct_answer": 1,
        "explanation": "의료기사는 의사 또는 치과의사의 지도 아래 업무를 수행한다.",
        "tags": ["법규", "업무범위"],
    },
    {
        "subject": "의료법규", "unit": "의료법", "difficulty": Difficulty.MEDIUM,
        "question_text": "의료법상 의료인이 아닌 직군은?",
        "choices": ["의사", "치과의사", "한의사", "물리치료사", "간호사"],
        "correct_answer": 3,
        "explanation": "의료인 5종: 의사, 치과의사, 한의사, 조산사, 간호사. 물리치료사는 의료기사.",
        "tags": ["법규", "의료인"],
    },
    {
        "subject": "의료법규", "unit": "감염병예방법", "difficulty": Difficulty.MEDIUM,
        "question_text": "감염병 예방을 위한 손위생의 가장 효과적인 방법은?",
        "choices": [
            "물로 30초 헹굼",
            "비누와 흐르는 물로 40~60초 손씻기",
            "알코올 손소독제(60% 이상)",
            "아무것도 안 함",
            "장갑만 착용",
        ],
        "correct_answer": 1,
        "explanation": "비누 + 흐르는 물 40~60초가 표준. 가시적 오염 없을 때 알코올 손소독제 사용.",
        "tags": ["법규", "감염예방"],
    },
    {
        "subject": "의료법규", "unit": "산재보험법", "difficulty": Difficulty.MEDIUM,
        "question_text": "산업재해보상보험에서 물리치료가 해당되는 급여는?",
        "choices": ["요양급여", "장해급여", "유족급여", "장의비", "휴업급여"],
        "correct_answer": 0,
        "explanation": "치료 자체는 요양급여에 해당.",
        "tags": ["법규", "산재"],
    },
    {
        "subject": "의료법규", "unit": "노인장기요양보험", "difficulty": Difficulty.MEDIUM,
        "question_text": "장기요양 등급 판정 기준이 아닌 것은?",
        "choices": [
            "신체기능",
            "인지기능",
            "행동변화",
            "간호처치",
            "월소득",
        ],
        "correct_answer": 4,
        "explanation": "장기요양 등급은 기능상태로 판정. 소득과 무관.",
        "tags": ["법규", "장기요양"],
    },
    {
        "subject": "의료법규", "unit": "의료기사법", "difficulty": Difficulty.HARD,
        "question_text": "물리치료사가 단독으로 개원할 수 있는가?",
        "choices": [
            "가능",
            "불가능 — 의료기관 내에서만 업무 가능",
            "교육 후 가능",
            "5년 경력 후 가능",
            "지자체 허가 시 가능",
        ],
        "correct_answer": 1,
        "explanation": "의료기사는 의료기관 내에서 의사의 지도 아래 업무 수행. 단독 개원 불가.",
        "tags": ["법규", "개원"],
    },
]
